/*
Cuckoo Sandbox - Automated Malware Analysis.
Copyright (C) 2010-2015 Cuckoo Foundation.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#include <stdint.h>
#include <winsock2.h>
#include <windows.h>
#include <winioctl.h>
#include <shlobj.h>
#include <wininet.h>
#include "flags.h"
#include "log.h"
#include "ntapi.h"


static const flag_repr_t _NtQueryValueKey_reg_type_value[] = {
    {REG_NONE, "REG_NONE"},
    {REG_SZ, "REG_SZ"},
    {REG_EXPAND_SZ, "REG_EXPAND_SZ"},
    {REG_BINARY, "REG_BINARY"},
    {REG_DWORD, "REG_DWORD"},
    {REG_DWORD_BIG_ENDIAN, "REG_DWORD_BIG_ENDIAN"},
    {REG_LINK, "REG_LINK"},
    {REG_MULTI_SZ, "REG_MULTI_SZ"},
    {REG_RESOURCE_LIST, "REG_RESOURCE_LIST"},
    {REG_FULL_RESOURCE_DESCRIPTOR, "REG_FULL_RESOURCE_DESCRIPTOR"},
    {REG_RESOURCE_REQUIREMENTS_LIST, "REG_RESOURCE_REQUIREMENTS_LIST"},
    {REG_QWORD, "REG_QWORD"},
    {0, NULL},
};

static const flag_repr_t _NtQueryValueKey_reg_type_bitmask[] = {
    {0, NULL},
};

static const flag_repr_t _RegQueryValueExW_lpType_value[] = {
    {REG_NONE, "REG_NONE"},
    {REG_SZ, "REG_SZ"},
    {REG_EXPAND_SZ, "REG_EXPAND_SZ"},
    {REG_BINARY, "REG_BINARY"},
    {REG_DWORD, "REG_DWORD"},
    {REG_DWORD_BIG_ENDIAN, "REG_DWORD_BIG_ENDIAN"},
    {REG_LINK, "REG_LINK"},
    {REG_MULTI_SZ, "REG_MULTI_SZ"},
    {REG_RESOURCE_LIST, "REG_RESOURCE_LIST"},
    {REG_FULL_RESOURCE_DESCRIPTOR, "REG_FULL_RESOURCE_DESCRIPTOR"},
    {REG_RESOURCE_REQUIREMENTS_LIST, "REG_RESOURCE_REQUIREMENTS_LIST"},
    {REG_QWORD, "REG_QWORD"},
    {0, NULL},
};

static const flag_repr_t _RegQueryValueExW_lpType_bitmask[] = {
    {0, NULL},
};

static const flag_repr_t _RegQueryValueExA_lpType_value[] = {
    {REG_NONE, "REG_NONE"},
    {REG_SZ, "REG_SZ"},
    {REG_EXPAND_SZ, "REG_EXPAND_SZ"},
    {REG_BINARY, "REG_BINARY"},
    {REG_DWORD, "REG_DWORD"},
    {REG_DWORD_BIG_ENDIAN, "REG_DWORD_BIG_ENDIAN"},
    {REG_LINK, "REG_LINK"},
    {REG_MULTI_SZ, "REG_MULTI_SZ"},
    {REG_RESOURCE_LIST, "REG_RESOURCE_LIST"},
    {REG_FULL_RESOURCE_DESCRIPTOR, "REG_FULL_RESOURCE_DESCRIPTOR"},
    {REG_RESOURCE_REQUIREMENTS_LIST, "REG_RESOURCE_REQUIREMENTS_LIST"},
    {REG_QWORD, "REG_QWORD"},
    {0, NULL},
};

static const flag_repr_t _RegQueryValueExA_lpType_bitmask[] = {
    {0, NULL},
};

static const flag_repr_t _NtAllocateVirtualMemory_Protect_value[] = {
    {0, NULL},
};

static const flag_repr_t _NtAllocateVirtualMemory_Protect_bitmask[] = {
    {PAGE_EXECUTE, "PAGE_EXECUTE"},
    {PAGE_EXECUTE_READ, "PAGE_EXECUTE_READ"},
    {PAGE_EXECUTE_READWRITE, "PAGE_EXECUTE_READWRITE"},
    {PAGE_EXECUTE_WRITECOPY, "PAGE_EXECUTE_WRITECOPY"},
    {PAGE_NOACCESS, "PAGE_NOACCESS"},
    {PAGE_READONLY, "PAGE_READONLY"},
    {PAGE_READWRITE, "PAGE_READWRITE"},
    {PAGE_WRITECOPY, "PAGE_WRITECOPY"},
    {PAGE_GUARD, "PAGE_GUARD"},
    {PAGE_NOCACHE, "PAGE_NOCACHE"},
    {PAGE_WRITECOMBINE, "PAGE_WRITECOMBINE"},
    {0, NULL},
};

static const flag_repr_t _InternetQueryOptions_value[] = {
    {INTERNET_OPTION_CALLBACK, "INTERNET_OPTION_CALLBACK"},
    {INTERNET_OPTION_CONNECT_TIMEOUT, "INTERNET_OPTION_CONNECT_TIMEOUT"},
    {INTERNET_OPTION_CONNECT_RETRIES, "INTERNET_OPTION_CONNECT_RETRIES"},
    {INTERNET_OPTION_CONNECT_BACKOFF, "INTERNET_OPTION_CONNECT_BACKOFF"},
    {INTERNET_OPTION_SEND_TIMEOUT, "INTERNET_OPTION_SEND_TIMEOUT"},
    {INTERNET_OPTION_CONTROL_SEND_TIMEOUT, "INTERNET_OPTION_CONTROL_SEND_TIMEOUT"},
    {INTERNET_OPTION_RECEIVE_TIMEOUT, "INTERNET_OPTION_RECEIVE_TIMEOUT"},
    {INTERNET_OPTION_CONTROL_RECEIVE_TIMEOUT, "INTERNET_OPTION_CONTROL_RECEIVE_TIMEOUT"},
    {INTERNET_OPTION_DATA_SEND_TIMEOUT, "INTERNET_OPTION_DATA_SEND_TIMEOUT"},
    {INTERNET_OPTION_DATA_RECEIVE_TIMEOUT, "INTERNET_OPTION_DATA_RECEIVE_TIMEOUT"},
    {INTERNET_OPTION_HANDLE_TYPE, "INTERNET_OPTION_HANDLE_TYPE"},
    {INTERNET_OPTION_LISTEN_TIMEOUT, "INTERNET_OPTION_LISTEN_TIMEOUT"},
    {INTERNET_OPTION_READ_BUFFER_SIZE, "INTERNET_OPTION_READ_BUFFER_SIZE"},
    {INTERNET_OPTION_WRITE_BUFFER_SIZE, "INTERNET_OPTION_WRITE_BUFFER_SIZE"},
    {INTERNET_OPTION_ASYNC_ID, "INTERNET_OPTION_ASYNC_ID"},
    {INTERNET_OPTION_ASYNC_PRIORITY, "INTERNET_OPTION_ASYNC_PRIORITY"},
    {INTERNET_OPTION_PARENT_HANDLE, "INTERNET_OPTION_PARENT_HANDLE"},
    {INTERNET_OPTION_KEEP_CONNECTION, "INTERNET_OPTION_KEEP_CONNECTION"},
    {INTERNET_OPTION_REQUEST_FLAGS, "INTERNET_OPTION_REQUEST_FLAGS"},
    {INTERNET_OPTION_EXTENDED_ERROR, "INTERNET_OPTION_EXTENDED_ERROR"},
    {INTERNET_OPTION_OFFLINE_MODE, "INTERNET_OPTION_OFFLINE_MODE"},
    {INTERNET_OPTION_CACHE_STREAM_HANDLE, "INTERNET_OPTION_CACHE_STREAM_HANDLE"},
    {INTERNET_OPTION_USERNAME, "INTERNET_OPTION_USERNAME"},
    {INTERNET_OPTION_PASSWORD, "INTERNET_OPTION_PASSWORD"},
    {INTERNET_OPTION_ASYNC, "INTERNET_OPTION_ASYNC"},
    {INTERNET_OPTION_SECURITY_FLAGS, "INTERNET_OPTION_SECURITY_FLAGS"},
    {INTERNET_OPTION_SECURITY_CERTIFICATE_STRUCT, "INTERNET_OPTION_SECURITY_CERTIFICATE_STRUCT"},
    {INTERNET_OPTION_DATAFILE_NAME, "INTERNET_OPTION_DATAFILE_NAME"},
    {INTERNET_OPTION_URL, "INTERNET_OPTION_URL"},
    {INTERNET_OPTION_SECURITY_CERTIFICATE, "INTERNET_OPTION_SECURITY_CERTIFICATE"},
    {INTERNET_OPTION_SECURITY_KEY_BITNESS, "INTERNET_OPTION_SECURITY_KEY_BITNESS"},
    {INTERNET_OPTION_REFRESH, "INTERNET_OPTION_REFRESH"},
    {INTERNET_OPTION_PROXY, "INTERNET_OPTION_PROXY"},
    {INTERNET_OPTION_SETTINGS_CHANGED, "INTERNET_OPTION_SETTINGS_CHANGED"},
    {INTERNET_OPTION_VERSION, "INTERNET_OPTION_VERSION"},
    {INTERNET_OPTION_USER_AGENT, "INTERNET_OPTION_USER_AGENT"},
    {INTERNET_OPTION_END_BROWSER_SESSION, "INTERNET_OPTION_END_BROWSER_SESSION"},
    {INTERNET_OPTION_PROXY_USERNAME, "INTERNET_OPTION_PROXY_USERNAME"},
    {INTERNET_OPTION_PROXY_PASSWORD, "INTERNET_OPTION_PROXY_PASSWORD"},
    {INTERNET_OPTION_CONTEXT_VALUE, "INTERNET_OPTION_CONTEXT_VALUE"},
    {INTERNET_OPTION_CONNECT_LIMIT, "INTERNET_OPTION_CONNECT_LIMIT"},
    {INTERNET_OPTION_SECURITY_SELECT_CLIENT_CERT, "INTERNET_OPTION_SECURITY_SELECT_CLIENT_CERT"},
    {INTERNET_OPTION_POLICY, "INTERNET_OPTION_POLICY"},
    {INTERNET_OPTION_DISCONNECTED_TIMEOUT, "INTERNET_OPTION_DISCONNECTED_TIMEOUT"},
    {INTERNET_OPTION_CONNECTED_STATE, "INTERNET_OPTION_CONNECTED_STATE"},
    {INTERNET_OPTION_IDLE_STATE, "INTERNET_OPTION_IDLE_STATE"},
    {INTERNET_OPTION_OFFLINE_SEMANTICS, "INTERNET_OPTION_OFFLINE_SEMANTICS"},
    {INTERNET_OPTION_SECONDARY_CACHE_KEY, "INTERNET_OPTION_SECONDARY_CACHE_KEY"},
    {INTERNET_OPTION_CALLBACK_FILTER, "INTERNET_OPTION_CALLBACK_FILTER"},
    {INTERNET_OPTION_CONNECT_TIME, "INTERNET_OPTION_CONNECT_TIME"},
    {INTERNET_OPTION_SEND_THROUGHPUT, "INTERNET_OPTION_SEND_THROUGHPUT"},
    {INTERNET_OPTION_RECEIVE_THROUGHPUT, "INTERNET_OPTION_RECEIVE_THROUGHPUT"},
    {INTERNET_OPTION_REQUEST_PRIORITY, "INTERNET_OPTION_REQUEST_PRIORITY"},
    {INTERNET_OPTION_HTTP_VERSION, "INTERNET_OPTION_HTTP_VERSION"},
    {INTERNET_OPTION_RESET_URLCACHE_SESSION, "INTERNET_OPTION_RESET_URLCACHE_SESSION"},
    {INTERNET_OPTION_ERROR_MASK, "INTERNET_OPTION_ERROR_MASK"},
    {INTERNET_OPTION_FROM_CACHE_TIMEOUT, "INTERNET_OPTION_FROM_CACHE_TIMEOUT"},
    {INTERNET_OPTION_BYPASS_EDITED_ENTRY, "INTERNET_OPTION_BYPASS_EDITED_ENTRY"},
    {INTERNET_OPTION_DIAGNOSTIC_SOCKET_INFO, "INTERNET_OPTION_DIAGNOSTIC_SOCKET_INFO"},
    {INTERNET_OPTION_CODEPAGE, "INTERNET_OPTION_CODEPAGE"},
    {INTERNET_OPTION_CACHE_TIMESTAMPS, "INTERNET_OPTION_CACHE_TIMESTAMPS"},
    {INTERNET_OPTION_DISABLE_AUTODIAL, "INTERNET_OPTION_DISABLE_AUTODIAL"},
    {INTERNET_OPTION_MAX_CONNS_PER_SERVER, "INTERNET_OPTION_MAX_CONNS_PER_SERVER"},
    {INTERNET_OPTION_MAX_CONNS_PER_1_0_SERVER, "INTERNET_OPTION_MAX_CONNS_PER_1_0_SERVER"},
    {INTERNET_OPTION_PER_CONNECTION_OPTION, "INTERNET_OPTION_PER_CONNECTION_OPTION"},
    {INTERNET_OPTION_DIGEST_AUTH_UNLOAD, "INTERNET_OPTION_DIGEST_AUTH_UNLOAD"},
    {INTERNET_OPTION_IGNORE_OFFLINE, "INTERNET_OPTION_IGNORE_OFFLINE"},
    {INTERNET_OPTION_IDENTITY, "INTERNET_OPTION_IDENTITY"},
    {INTERNET_OPTION_REMOVE_IDENTITY, "INTERNET_OPTION_REMOVE_IDENTITY"},
    {INTERNET_OPTION_ALTER_IDENTITY, "INTERNET_OPTION_ALTER_IDENTITY"},
    {INTERNET_OPTION_SUPPRESS_BEHAVIOR, "INTERNET_OPTION_SUPPRESS_BEHAVIOR"},
    {INTERNET_OPTION_AUTODIAL_MODE, "INTERNET_OPTION_AUTODIAL_MODE"},
    {INTERNET_OPTION_AUTODIAL_CONNECTION, "INTERNET_OPTION_AUTODIAL_CONNECTION"},
    {INTERNET_OPTION_CLIENT_CERT_CONTEXT, "INTERNET_OPTION_CLIENT_CERT_CONTEXT"},
    {INTERNET_OPTION_AUTH_FLAGS, "INTERNET_OPTION_AUTH_FLAGS"},
    {INTERNET_OPTION_COOKIES_3RD_PARTY, "INTERNET_OPTION_COOKIES_3RD_PARTY"},
    {INTERNET_OPTION_DISABLE_PASSPORT_AUTH, "INTERNET_OPTION_DISABLE_PASSPORT_AUTH"},
    {INTERNET_OPTION_SEND_UTF8_SERVERNAME_TO_PROXY, "INTERNET_OPTION_SEND_UTF8_SERVERNAME_TO_PROXY"},
    {INTERNET_OPTION_EXEMPT_CONNECTION_LIMIT, "INTERNET_OPTION_EXEMPT_CONNECTION_LIMIT"},
    {INTERNET_OPTION_ENABLE_PASSPORT_AUTH, "INTERNET_OPTION_ENABLE_PASSPORT_AUTH"},
    {INTERNET_OPTION_HIBERNATE_INACTIVE_WORKER_THREADS, "INTERNET_OPTION_HIBERNATE_INACTIVE_WORKER_THREADS"},
    {INTERNET_OPTION_ACTIVATE_WORKER_THREADS, "INTERNET_OPTION_ACTIVATE_WORKER_THREADS"},
    {INTERNET_OPTION_RESTORE_WORKER_THREAD_DEFAULTS, "INTERNET_OPTION_RESTORE_WORKER_THREAD_DEFAULTS"},
    {INTERNET_OPTION_SOCKET_SEND_BUFFER_LENGTH, "INTERNET_OPTION_SOCKET_SEND_BUFFER_LENGTH"},
    {INTERNET_OPTION_PROXY_SETTINGS_CHANGED, "INTERNET_OPTION_PROXY_SETTINGS_CHANGED"},
    {INTERNET_OPTION_DATAFILE_EXT, "INTERNET_OPTION_DATAFILE_EXT"},
    {0, NULL},
};

static const flag_repr_t _InternetQueryOptions_bitmask[] = {
    {0, NULL},
};

static const flag_repr_t _RegSetValueExA_dwType_value[] = {
    {REG_NONE, "REG_NONE"},
    {REG_SZ, "REG_SZ"},
    {REG_EXPAND_SZ, "REG_EXPAND_SZ"},
    {REG_BINARY, "REG_BINARY"},
    {REG_DWORD, "REG_DWORD"},
    {REG_DWORD_BIG_ENDIAN, "REG_DWORD_BIG_ENDIAN"},
    {REG_LINK, "REG_LINK"},
    {REG_MULTI_SZ, "REG_MULTI_SZ"},
    {REG_RESOURCE_LIST, "REG_RESOURCE_LIST"},
    {REG_FULL_RESOURCE_DESCRIPTOR, "REG_FULL_RESOURCE_DESCRIPTOR"},
    {REG_RESOURCE_REQUIREMENTS_LIST, "REG_RESOURCE_REQUIREMENTS_LIST"},
    {REG_QWORD, "REG_QWORD"},
    {0, NULL},
};

static const flag_repr_t _RegSetValueExA_dwType_bitmask[] = {
    {0, NULL},
};

static const flag_repr_t _FILE_INFORMATION_CLASS_value[] = {
    {FileDirectoryInformation, "FileDirectoryInformation"},
    {FileFullDirectoryInformation, "FileFullDirectoryInformation"},
    {FileBothDirectoryInformation, "FileBothDirectoryInformation"},
    {FileBasicInformation, "FileBasicInformation"},
    {FileStandardInformation, "FileStandardInformation"},
    {FileInternalInformation, "FileInternalInformation"},
    {FileEaInformation, "FileEaInformation"},
    {FileAccessInformation, "FileAccessInformation"},
    {FileNameInformation, "FileNameInformation"},
    {FileRenameInformation, "FileRenameInformation"},
    {FileLinkInformation, "FileLinkInformation"},
    {FileNamesInformation, "FileNamesInformation"},
    {FileDispositionInformation, "FileDispositionInformation"},
    {FilePositionInformation, "FilePositionInformation"},
    {FileFullEaInformation, "FileFullEaInformation"},
    {FileModeInformation, "FileModeInformation"},
    {FileAlignmentInformation, "FileAlignmentInformation"},
    {FileAllInformation, "FileAllInformation"},
    {FileAllocationInformation, "FileAllocationInformation"},
    {FileEndOfFileInformation, "FileEndOfFileInformation"},
    {FileAlternateNameInformation, "FileAlternateNameInformation"},
    {FileStreamInformation, "FileStreamInformation"},
    {FilePipeInformation, "FilePipeInformation"},
    {FilePipeLocalInformation, "FilePipeLocalInformation"},
    {FilePipeRemoteInformation, "FilePipeRemoteInformation"},
    {FileMailslotQueryInformation, "FileMailslotQueryInformation"},
    {FileMailslotSetInformation, "FileMailslotSetInformation"},
    {FileCompressionInformation, "FileCompressionInformation"},
    {FileObjectIdInformation, "FileObjectIdInformation"},
    {FileCompletionInformation, "FileCompletionInformation"},
    {FileMoveClusterInformation, "FileMoveClusterInformation"},
    {FileQuotaInformation, "FileQuotaInformation"},
    {FileReparsePointInformation, "FileReparsePointInformation"},
    {FileNetworkOpenInformation, "FileNetworkOpenInformation"},
    {FileAttributeTagInformation, "FileAttributeTagInformation"},
    {FileTrackingInformation, "FileTrackingInformation"},
    {FileIdBothDirectoryInformation, "FileIdBothDirectoryInformation"},
    {FileIdFullDirectoryInformation, "FileIdFullDirectoryInformation"},
    {FileValidDataLengthInformation, "FileValidDataLengthInformation"},
    {FileShortNameInformation, "FileShortNameInformation"},
    {FileIoCompletionNotificationInformation, "FileIoCompletionNotificationInformation"},
    {FileIoStatusBlockRangeInformation, "FileIoStatusBlockRangeInformation"},
    {FileIoPriorityHintInformation, "FileIoPriorityHintInformation"},
    {FileSfioReserveInformation, "FileSfioReserveInformation"},
    {FileSfioVolumeInformation, "FileSfioVolumeInformation"},
    {FileHardLinkInformation, "FileHardLinkInformation"},
    {FileProcessIdsUsingFileInformation, "FileProcessIdsUsingFileInformation"},
    {FileNormalizedNameInformation, "FileNormalizedNameInformation"},
    {FileNetworkPhysicalNameInformation, "FileNetworkPhysicalNameInformation"},
    {FileIdGlobalTxDirectoryInformation, "FileIdGlobalTxDirectoryInformation"},
    {FileIsRemoteDeviceInformation, "FileIsRemoteDeviceInformation"},
    {FileAttributeCacheInformation, "FileAttributeCacheInformation"},
    {FileNumaNodeInformation, "FileNumaNodeInformation"},
    {FileStandardLinkInformation, "FileStandardLinkInformation"},
    {FileRemoteProtocolInformation, "FileRemoteProtocolInformation"},
    {0, NULL},
};

static const flag_repr_t _FILE_INFORMATION_CLASS_bitmask[] = {
    {0, NULL},
};

static const flag_repr_t _NtCreateFile_FileAttributes_value[] = {
    {0, NULL},
};

static const flag_repr_t _NtCreateFile_FileAttributes_bitmask[] = {
    {FILE_ATTRIBUTE_ARCHIVE, "FILE_ATTRIBUTE_ARCHIVE"},
    {FILE_ATTRIBUTE_ENCRYPTED, "FILE_ATTRIBUTE_ENCRYPTED"},
    {FILE_ATTRIBUTE_HIDDEN, "FILE_ATTRIBUTE_HIDDEN"},
    {FILE_ATTRIBUTE_NORMAL, "FILE_ATTRIBUTE_NORMAL"},
    {FILE_ATTRIBUTE_OFFLINE, "FILE_ATTRIBUTE_OFFLINE"},
    {FILE_ATTRIBUTE_READONLY, "FILE_ATTRIBUTE_READONLY"},
    {FILE_ATTRIBUTE_SYSTEM, "FILE_ATTRIBUTE_SYSTEM"},
    {FILE_ATTRIBUTE_TEMPORARY, "FILE_ATTRIBUTE_TEMPORARY"},
    {FILE_FLAG_BACKUP_SEMANTICS, "FILE_FLAG_BACKUP_SEMANTICS"},
    {FILE_FLAG_DELETE_ON_CLOSE, "FILE_FLAG_DELETE_ON_CLOSE"},
    {FILE_FLAG_NO_BUFFERING, "FILE_FLAG_NO_BUFFERING"},
    {FILE_FLAG_OPEN_NO_RECALL, "FILE_FLAG_OPEN_NO_RECALL"},
    {FILE_FLAG_OPEN_REPARSE_POINT, "FILE_FLAG_OPEN_REPARSE_POINT"},
    {FILE_FLAG_OVERLAPPED, "FILE_FLAG_OVERLAPPED"},
    {FILE_FLAG_POSIX_SEMANTICS, "FILE_FLAG_POSIX_SEMANTICS"},
    {FILE_FLAG_RANDOM_ACCESS, "FILE_FLAG_RANDOM_ACCESS"},
    {FILE_FLAG_SESSION_AWARE, "FILE_FLAG_SESSION_AWARE"},
    {FILE_FLAG_SEQUENTIAL_SCAN, "FILE_FLAG_SEQUENTIAL_SCAN"},
    {FILE_FLAG_WRITE_THROUGH, "FILE_FLAG_WRITE_THROUGH"},
    {0, NULL},
};

static const flag_repr_t _SetFileAttributesW_dwFileAttributes_value[] = {
    {0, NULL},
};

static const flag_repr_t _SetFileAttributesW_dwFileAttributes_bitmask[] = {
    {FILE_ATTRIBUTE_ARCHIVE, "FILE_ATTRIBUTE_ARCHIVE"},
    {FILE_ATTRIBUTE_HIDDEN, "FILE_ATTRIBUTE_HIDDEN"},
    {FILE_ATTRIBUTE_NORMAL, "FILE_ATTRIBUTE_NORMAL"},
    {FILE_ATTRIBUTE_NOT_CONTENT_INDEXED, "FILE_ATTRIBUTE_NOT_CONTENT_INDEXED"},
    {FILE_ATTRIBUTE_OFFLINE, "FILE_ATTRIBUTE_OFFLINE"},
    {FILE_ATTRIBUTE_READONLY, "FILE_ATTRIBUTE_READONLY"},
    {FILE_ATTRIBUTE_SYSTEM, "FILE_ATTRIBUTE_SYSTEM"},
    {FILE_ATTRIBUTE_TEMPORARY, "FILE_ATTRIBUTE_TEMPORARY"},
    {0, NULL},
};

static const flag_repr_t _NtCreateFile_DesiredAccess_value[] = {
    {0, NULL},
};

static const flag_repr_t _NtCreateFile_DesiredAccess_bitmask[] = {
    {FILE_READ_DATA, "FILE_READ_DATA"},
    {FILE_READ_ATTRIBUTES, "FILE_READ_ATTRIBUTES"},
    {FILE_READ_EA, "FILE_READ_EA"},
    {FILE_WRITE_DATA, "FILE_WRITE_DATA"},
    {FILE_WRITE_ATTRIBUTES, "FILE_WRITE_ATTRIBUTES"},
    {FILE_WRITE_EA, "FILE_WRITE_EA"},
    {FILE_APPEND_DATA, "FILE_APPEND_DATA"},
    {FILE_EXECUTE, "FILE_EXECUTE"},
    {FILE_LIST_DIRECTORY, "FILE_LIST_DIRECTORY"},
    {FILE_TRAVERSE, "FILE_TRAVERSE"},
    {STANDARD_RIGHTS_ALL, "STANDARD_RIGHTS_ALL"},
    {STANDARD_RIGHTS_REQUIRED, "STANDARD_RIGHTS_REQUIRED"},
    {DELETE, "DELETE"},
    {READ_CONTROL, "READ_CONTROL"},
    {WRITE_DAC, "WRITE_DAC"},
    {WRITE_OWNER, "WRITE_OWNER"},
    {SYNCHRONIZE, "SYNCHRONIZE"},
    {SPECIFIC_RIGHTS_ALL, "SPECIFIC_RIGHTS_ALL"},
    {ACCESS_SYSTEM_SECURITY, "ACCESS_SYSTEM_SECURITY"},
    {MAXIMUM_ALLOWED, "MAXIMUM_ALLOWED"},
    {GENERIC_READ, "GENERIC_READ"},
    {GENERIC_WRITE, "GENERIC_WRITE"},
    {GENERIC_EXECUTE, "GENERIC_EXECUTE"},
    {GENERIC_ALL, "GENERIC_ALL"},
    {0, NULL},
};

static const flag_repr_t _NtOpenFile_OpenOptions_value[] = {
    {0, NULL},
};

static const flag_repr_t _NtOpenFile_OpenOptions_bitmask[] = {
    {FILE_DIRECTORY_FILE, "FILE_DIRECTORY_FILE"},
    {FILE_NON_DIRECTORY_FILE, "FILE_NON_DIRECTORY_FILE"},
    {FILE_WRITE_THROUGH, "FILE_WRITE_THROUGH"},
    {FILE_SEQUENTIAL_ONLY, "FILE_SEQUENTIAL_ONLY"},
    {FILE_RANDOM_ACCESS, "FILE_RANDOM_ACCESS"},
    {FILE_NO_INTERMEDIATE_BUFFERING, "FILE_NO_INTERMEDIATE_BUFFERING"},
    {FILE_SYNCHRONOUS_IO_ALERT, "FILE_SYNCHRONOUS_IO_ALERT"},
    {FILE_SYNCHRONOUS_IO_NONALERT, "FILE_SYNCHRONOUS_IO_NONALERT"},
    {FILE_CREATE_TREE_CONNECTION, "FILE_CREATE_TREE_CONNECTION"},
    {FILE_COMPLETE_IF_OPLOCKED, "FILE_COMPLETE_IF_OPLOCKED"},
    {FILE_NO_EA_KNOWLEDGE, "FILE_NO_EA_KNOWLEDGE"},
    {FILE_OPEN_REPARSE_POINT, "FILE_OPEN_REPARSE_POINT"},
    {FILE_DELETE_ON_CLOSE, "FILE_DELETE_ON_CLOSE"},
    {FILE_OPEN_BY_FILE_ID, "FILE_OPEN_BY_FILE_ID"},
    {FILE_OPEN_FOR_BACKUP_INTENT, "FILE_OPEN_FOR_BACKUP_INTENT"},
    {FILE_RESERVE_OPFILTER, "FILE_RESERVE_OPFILTER"},
    {0, NULL},
};

static const flag_repr_t _NtCreateFile_CreateOptions_value[] = {
    {0, NULL},
};

static const flag_repr_t _NtCreateFile_CreateOptions_bitmask[] = {
    {FILE_DIRECTORY_FILE, "FILE_DIRECTORY_FILE"},
    {FILE_NON_DIRECTORY_FILE, "FILE_NON_DIRECTORY_FILE"},
    {FILE_WRITE_THROUGH, "FILE_WRITE_THROUGH"},
    {FILE_SEQUENTIAL_ONLY, "FILE_SEQUENTIAL_ONLY"},
    {FILE_RANDOM_ACCESS, "FILE_RANDOM_ACCESS"},
    {FILE_NO_INTERMEDIATE_BUFFERING, "FILE_NO_INTERMEDIATE_BUFFERING"},
    {FILE_SYNCHRONOUS_IO_ALERT, "FILE_SYNCHRONOUS_IO_ALERT"},
    {FILE_SYNCHRONOUS_IO_NONALERT, "FILE_SYNCHRONOUS_IO_NONALERT"},
    {FILE_CREATE_TREE_CONNECTION, "FILE_CREATE_TREE_CONNECTION"},
    {FILE_COMPLETE_IF_OPLOCKED, "FILE_COMPLETE_IF_OPLOCKED"},
    {FILE_NO_EA_KNOWLEDGE, "FILE_NO_EA_KNOWLEDGE"},
    {FILE_OPEN_REPARSE_POINT, "FILE_OPEN_REPARSE_POINT"},
    {FILE_DELETE_ON_CLOSE, "FILE_DELETE_ON_CLOSE"},
    {FILE_OPEN_BY_FILE_ID, "FILE_OPEN_BY_FILE_ID"},
    {FILE_OPEN_FOR_BACKUP_INTENT, "FILE_OPEN_FOR_BACKUP_INTENT"},
    {FILE_RESERVE_OPFILTER, "FILE_RESERVE_OPFILTER"},
    {0, NULL},
};

static const flag_repr_t _NtOpenFile_DesiredAccess_value[] = {
    {0, NULL},
};

static const flag_repr_t _NtOpenFile_DesiredAccess_bitmask[] = {
    {FILE_READ_DATA, "FILE_READ_DATA"},
    {FILE_READ_ATTRIBUTES, "FILE_READ_ATTRIBUTES"},
    {FILE_READ_EA, "FILE_READ_EA"},
    {FILE_WRITE_DATA, "FILE_WRITE_DATA"},
    {FILE_WRITE_ATTRIBUTES, "FILE_WRITE_ATTRIBUTES"},
    {FILE_WRITE_EA, "FILE_WRITE_EA"},
    {FILE_APPEND_DATA, "FILE_APPEND_DATA"},
    {FILE_EXECUTE, "FILE_EXECUTE"},
    {FILE_LIST_DIRECTORY, "FILE_LIST_DIRECTORY"},
    {FILE_TRAVERSE, "FILE_TRAVERSE"},
    {STANDARD_RIGHTS_ALL, "STANDARD_RIGHTS_ALL"},
    {STANDARD_RIGHTS_REQUIRED, "STANDARD_RIGHTS_REQUIRED"},
    {DELETE, "DELETE"},
    {READ_CONTROL, "READ_CONTROL"},
    {WRITE_DAC, "WRITE_DAC"},
    {WRITE_OWNER, "WRITE_OWNER"},
    {SYNCHRONIZE, "SYNCHRONIZE"},
    {SPECIFIC_RIGHTS_ALL, "SPECIFIC_RIGHTS_ALL"},
    {ACCESS_SYSTEM_SECURITY, "ACCESS_SYSTEM_SECURITY"},
    {MAXIMUM_ALLOWED, "MAXIMUM_ALLOWED"},
    {GENERIC_READ, "GENERIC_READ"},
    {GENERIC_WRITE, "GENERIC_WRITE"},
    {GENERIC_EXECUTE, "GENERIC_EXECUTE"},
    {GENERIC_ALL, "GENERIC_ALL"},
    {0, NULL},
};

static const flag_repr_t _NtEnumerateValueKey_reg_type_value[] = {
    {REG_NONE, "REG_NONE"},
    {REG_SZ, "REG_SZ"},
    {REG_EXPAND_SZ, "REG_EXPAND_SZ"},
    {REG_BINARY, "REG_BINARY"},
    {REG_DWORD, "REG_DWORD"},
    {REG_DWORD_BIG_ENDIAN, "REG_DWORD_BIG_ENDIAN"},
    {REG_LINK, "REG_LINK"},
    {REG_MULTI_SZ, "REG_MULTI_SZ"},
    {REG_RESOURCE_LIST, "REG_RESOURCE_LIST"},
    {REG_FULL_RESOURCE_DESCRIPTOR, "REG_FULL_RESOURCE_DESCRIPTOR"},
    {REG_RESOURCE_REQUIREMENTS_LIST, "REG_RESOURCE_REQUIREMENTS_LIST"},
    {REG_QWORD, "REG_QWORD"},
    {0, NULL},
};

static const flag_repr_t _NtEnumerateValueKey_reg_type_bitmask[] = {
    {0, NULL},
};

static const flag_repr_t _CreateWindowExW_dwExStyle_value[] = {
    {WS_EX_OVERLAPPEDWINDOW, "WS_EX_OVERLAPPEDWINDOW"},
    {WS_EX_PALETTEWINDOW, "WS_EX_PALETTEWINDOW"},
    {0, NULL},
};

static const flag_repr_t _CreateWindowExW_dwExStyle_bitmask[] = {
    {WS_EX_DLGMODALFRAME, "WS_EX_DLGMODALFRAME"},
    {WS_EX_NOPARENTNOTIFY, "WS_EX_NOPARENTNOTIFY"},
    {WS_EX_TOPMOST, "WS_EX_TOPMOST"},
    {WS_EX_ACCEPTFILES, "WS_EX_ACCEPTFILES"},
    {WS_EX_TRANSPARENT, "WS_EX_TRANSPARENT"},
    {WS_EX_MDICHILD, "WS_EX_MDICHILD"},
    {WS_EX_TOOLWINDOW, "WS_EX_TOOLWINDOW"},
    {WS_EX_WINDOWEDGE, "WS_EX_WINDOWEDGE"},
    {WS_EX_CLIENTEDGE, "WS_EX_CLIENTEDGE"},
    {WS_EX_CONTEXTHELP, "WS_EX_CONTEXTHELP"},
    {WS_EX_RIGHT, "WS_EX_RIGHT"},
    {WS_EX_LEFT, "WS_EX_LEFT"},
    {WS_EX_RTLREADING, "WS_EX_RTLREADING"},
    {WS_EX_LTRREADING, "WS_EX_LTRREADING"},
    {WS_EX_LEFTSCROLLBAR, "WS_EX_LEFTSCROLLBAR"},
    {WS_EX_RIGHTSCROLLBAR, "WS_EX_RIGHTSCROLLBAR"},
    {WS_EX_CONTROLPARENT, "WS_EX_CONTROLPARENT"},
    {WS_EX_STATICEDGE, "WS_EX_STATICEDGE"},
    {WS_EX_APPWINDOW, "WS_EX_APPWINDOW"},
    {WS_EX_LAYERED, "WS_EX_LAYERED"},
    {WS_EX_NOINHERITLAYOUT, "WS_EX_NOINHERITLAYOUT"},
    {WS_EX_LAYOUTRTL, "WS_EX_LAYOUTRTL"},
    {WS_EX_COMPOSITED, "WS_EX_COMPOSITED"},
    {WS_EX_NOACTIVATE, "WS_EX_NOACTIVATE"},
    {0, NULL},
};

static const flag_repr_t _GetSystemMetrics_nIndex_value[] = {
    {SM_CXSCREEN, "SM_CXSCREEN"},
    {SM_CYSCREEN, "SM_CYSCREEN"},
    {SM_CXVSCROLL, "SM_CXVSCROLL"},
    {SM_CYHSCROLL, "SM_CYHSCROLL"},
    {SM_CYCAPTION, "SM_CYCAPTION"},
    {SM_CXBORDER, "SM_CXBORDER"},
    {SM_CYBORDER, "SM_CYBORDER"},
    {SM_CXDLGFRAME, "SM_CXDLGFRAME"},
    {SM_CYDLGFRAME, "SM_CYDLGFRAME"},
    {SM_CYVTHUMB, "SM_CYVTHUMB"},
    {SM_CXHTHUMB, "SM_CXHTHUMB"},
    {SM_CXICON, "SM_CXICON"},
    {SM_CYICON, "SM_CYICON"},
    {SM_CXCURSOR, "SM_CXCURSOR"},
    {SM_CYCURSOR, "SM_CYCURSOR"},
    {SM_CYMENU, "SM_CYMENU"},
    {SM_CXFULLSCREEN, "SM_CXFULLSCREEN"},
    {SM_CYFULLSCREEN, "SM_CYFULLSCREEN"},
    {SM_CYKANJIWINDOW, "SM_CYKANJIWINDOW"},
    {SM_MOUSEPRESENT, "SM_MOUSEPRESENT"},
    {SM_CYVSCROLL, "SM_CYVSCROLL"},
    {SM_CXHSCROLL, "SM_CXHSCROLL"},
    {SM_DEBUG, "SM_DEBUG"},
    {SM_SWAPBUTTON, "SM_SWAPBUTTON"},
    {SM_RESERVED1, "SM_RESERVED1"},
    {SM_RESERVED2, "SM_RESERVED2"},
    {SM_RESERVED3, "SM_RESERVED3"},
    {SM_RESERVED4, "SM_RESERVED4"},
    {SM_CXMIN, "SM_CXMIN"},
    {SM_CYMIN, "SM_CYMIN"},
    {SM_CXSIZE, "SM_CXSIZE"},
    {SM_CYSIZE, "SM_CYSIZE"},
    {SM_CXFRAME, "SM_CXFRAME"},
    {SM_CYFRAME, "SM_CYFRAME"},
    {SM_CXMINTRACK, "SM_CXMINTRACK"},
    {SM_CYMINTRACK, "SM_CYMINTRACK"},
    {SM_CXDOUBLECLK, "SM_CXDOUBLECLK"},
    {SM_CYDOUBLECLK, "SM_CYDOUBLECLK"},
    {SM_CXICONSPACING, "SM_CXICONSPACING"},
    {SM_CYICONSPACING, "SM_CYICONSPACING"},
    {SM_MENUDROPALIGNMENT, "SM_MENUDROPALIGNMENT"},
    {SM_PENWINDOWS, "SM_PENWINDOWS"},
    {SM_DBCSENABLED, "SM_DBCSENABLED"},
    {SM_CMOUSEBUTTONS, "SM_CMOUSEBUTTONS"},
    {SM_SECURE, "SM_SECURE"},
    {SM_CXEDGE, "SM_CXEDGE"},
    {SM_CYEDGE, "SM_CYEDGE"},
    {SM_CXMINSPACING, "SM_CXMINSPACING"},
    {SM_CYMINSPACING, "SM_CYMINSPACING"},
    {SM_CXSMICON, "SM_CXSMICON"},
    {SM_CYSMICON, "SM_CYSMICON"},
    {SM_CYSMCAPTION, "SM_CYSMCAPTION"},
    {SM_CXSMSIZE, "SM_CXSMSIZE"},
    {SM_CYSMSIZE, "SM_CYSMSIZE"},
    {SM_CXMENUSIZE, "SM_CXMENUSIZE"},
    {SM_CYMENUSIZE, "SM_CYMENUSIZE"},
    {SM_ARRANGE, "SM_ARRANGE"},
    {SM_CXMINIMIZED, "SM_CXMINIMIZED"},
    {SM_CYMINIMIZED, "SM_CYMINIMIZED"},
    {SM_CXMAXTRACK, "SM_CXMAXTRACK"},
    {SM_CYMAXTRACK, "SM_CYMAXTRACK"},
    {SM_CXMAXIMIZED, "SM_CXMAXIMIZED"},
    {SM_CYMAXIMIZED, "SM_CYMAXIMIZED"},
    {SM_NETWORK, "SM_NETWORK"},
    {SM_CLEANBOOT, "SM_CLEANBOOT"},
    {SM_CXDRAG, "SM_CXDRAG"},
    {SM_CYDRAG, "SM_CYDRAG"},
    {SM_SHOWSOUNDS, "SM_SHOWSOUNDS"},
    {SM_CXMENUCHECK, "SM_CXMENUCHECK"},
    {SM_CYMENUCHECK, "SM_CYMENUCHECK"},
    {SM_SLOWMACHINE, "SM_SLOWMACHINE"},
    {SM_MIDEASTENABLED, "SM_MIDEASTENABLED"},
    {SM_MOUSEWHEELPRESENT, "SM_MOUSEWHEELPRESENT"},
    {SM_XVIRTUALSCREEN, "SM_XVIRTUALSCREEN"},
    {SM_YVIRTUALSCREEN, "SM_YVIRTUALSCREEN"},
    {SM_CXVIRTUALSCREEN, "SM_CXVIRTUALSCREEN"},
    {SM_CYVIRTUALSCREEN, "SM_CYVIRTUALSCREEN"},
    {SM_CMONITORS, "SM_CMONITORS"},
    {SM_SAMEDISPLAYFORMAT, "SM_SAMEDISPLAYFORMAT"},
    {SM_IMMENABLED, "SM_IMMENABLED"},
    {SM_CXFOCUSBORDER, "SM_CXFOCUSBORDER"},
    {SM_CYFOCUSBORDER, "SM_CYFOCUSBORDER"},
    {SM_TABLETPC, "SM_TABLETPC"},
    {SM_MEDIACENTER, "SM_MEDIACENTER"},
    {SM_STARTER, "SM_STARTER"},
    {SM_SERVERR2, "SM_SERVERR2"},
    {SM_REMOTESESSION, "SM_REMOTESESSION"},
    {SM_SHUTTINGDOWN, "SM_SHUTTINGDOWN"},
    {SM_REMOTECONTROL, "SM_REMOTECONTROL"},
    {SM_CARETBLINKINGENABLED, "SM_CARETBLINKINGENABLED"},
    {0, NULL},
};

static const flag_repr_t _GetSystemMetrics_nIndex_bitmask[] = {
    {0, NULL},
};

static const flag_repr_t _NtMapViewOfSection_AllocationType_value[] = {
    {0, NULL},
};

static const flag_repr_t _NtMapViewOfSection_AllocationType_bitmask[] = {
    {MEM_COMMIT, "MEM_COMMIT"},
    {MEM_RESERVE, "MEM_RESERVE"},
    {MEM_RESET, "MEM_RESET"},
    {MEM_LARGE_PAGES, "MEM_LARGE_PAGES"},
    {MEM_PHYSICAL, "MEM_PHYSICAL"},
    {MEM_TOP_DOWN, "MEM_TOP_DOWN"},
    {MEM_WRITE_WATCH, "MEM_WRITE_WATCH"},
    {0, NULL},
};

static const flag_repr_t _NtDeviceIoControlFile_IoControlCode_value[] = {
    {IOCTL_STORAGE_CHECK_VERIFY, "IOCTL_STORAGE_CHECK_VERIFY"},
    {IOCTL_STORAGE_CHECK_VERIFY2, "IOCTL_STORAGE_CHECK_VERIFY2"},
    {IOCTL_STORAGE_MEDIA_REMOVAL, "IOCTL_STORAGE_MEDIA_REMOVAL"},
    {IOCTL_STORAGE_EJECT_MEDIA, "IOCTL_STORAGE_EJECT_MEDIA"},
    {IOCTL_STORAGE_LOAD_MEDIA, "IOCTL_STORAGE_LOAD_MEDIA"},
    {IOCTL_STORAGE_LOAD_MEDIA2, "IOCTL_STORAGE_LOAD_MEDIA2"},
    {IOCTL_STORAGE_RESERVE, "IOCTL_STORAGE_RESERVE"},
    {IOCTL_STORAGE_RELEASE, "IOCTL_STORAGE_RELEASE"},
    {IOCTL_STORAGE_FIND_NEW_DEVICES, "IOCTL_STORAGE_FIND_NEW_DEVICES"},
    {IOCTL_STORAGE_EJECTION_CONTROL, "IOCTL_STORAGE_EJECTION_CONTROL"},
    {IOCTL_STORAGE_MCN_CONTROL, "IOCTL_STORAGE_MCN_CONTROL"},
    {IOCTL_STORAGE_GET_MEDIA_TYPES, "IOCTL_STORAGE_GET_MEDIA_TYPES"},
    {IOCTL_STORAGE_GET_MEDIA_TYPES_EX, "IOCTL_STORAGE_GET_MEDIA_TYPES_EX"},
    {IOCTL_STORAGE_GET_MEDIA_SERIAL_NUMBER, "IOCTL_STORAGE_GET_MEDIA_SERIAL_NUMBER"},
    {IOCTL_STORAGE_GET_HOTPLUG_INFO, "IOCTL_STORAGE_GET_HOTPLUG_INFO"},
    {IOCTL_STORAGE_SET_HOTPLUG_INFO, "IOCTL_STORAGE_SET_HOTPLUG_INFO"},
    {IOCTL_STORAGE_RESET_BUS, "IOCTL_STORAGE_RESET_BUS"},
    {IOCTL_STORAGE_RESET_DEVICE, "IOCTL_STORAGE_RESET_DEVICE"},
    {IOCTL_STORAGE_BREAK_RESERVATION, "IOCTL_STORAGE_BREAK_RESERVATION"},
    {IOCTL_STORAGE_GET_DEVICE_NUMBER, "IOCTL_STORAGE_GET_DEVICE_NUMBER"},
    {IOCTL_STORAGE_PREDICT_FAILURE, "IOCTL_STORAGE_PREDICT_FAILURE"},
    {IOCTL_STORAGE_READ_CAPACITY, "IOCTL_STORAGE_READ_CAPACITY"},
    {IOCTL_DISK_GET_DRIVE_GEOMETRY, "IOCTL_DISK_GET_DRIVE_GEOMETRY"},
    {IOCTL_DISK_GET_PARTITION_INFO, "IOCTL_DISK_GET_PARTITION_INFO"},
    {IOCTL_DISK_SET_PARTITION_INFO, "IOCTL_DISK_SET_PARTITION_INFO"},
    {IOCTL_DISK_GET_DRIVE_LAYOUT, "IOCTL_DISK_GET_DRIVE_LAYOUT"},
    {IOCTL_DISK_SET_DRIVE_LAYOUT, "IOCTL_DISK_SET_DRIVE_LAYOUT"},
    {IOCTL_DISK_VERIFY, "IOCTL_DISK_VERIFY"},
    {IOCTL_DISK_FORMAT_TRACKS, "IOCTL_DISK_FORMAT_TRACKS"},
    {IOCTL_DISK_REASSIGN_BLOCKS, "IOCTL_DISK_REASSIGN_BLOCKS"},
    {IOCTL_DISK_PERFORMANCE, "IOCTL_DISK_PERFORMANCE"},
    {IOCTL_DISK_IS_WRITABLE, "IOCTL_DISK_IS_WRITABLE"},
    {IOCTL_DISK_LOGGING, "IOCTL_DISK_LOGGING"},
    {IOCTL_DISK_FORMAT_TRACKS_EX, "IOCTL_DISK_FORMAT_TRACKS_EX"},
    {IOCTL_DISK_HISTOGRAM_STRUCTURE, "IOCTL_DISK_HISTOGRAM_STRUCTURE"},
    {IOCTL_DISK_HISTOGRAM_DATA, "IOCTL_DISK_HISTOGRAM_DATA"},
    {IOCTL_DISK_HISTOGRAM_RESET, "IOCTL_DISK_HISTOGRAM_RESET"},
    {IOCTL_DISK_REQUEST_STRUCTURE, "IOCTL_DISK_REQUEST_STRUCTURE"},
    {IOCTL_DISK_REQUEST_DATA, "IOCTL_DISK_REQUEST_DATA"},
    {IOCTL_DISK_PERFORMANCE_OFF, "IOCTL_DISK_PERFORMANCE_OFF"},
    {IOCTL_DISK_CONTROLLER_NUMBER, "IOCTL_DISK_CONTROLLER_NUMBER"},
    {IOCTL_DISK_GET_PARTITION_INFO_EX, "IOCTL_DISK_GET_PARTITION_INFO_EX"},
    {IOCTL_DISK_SET_PARTITION_INFO_EX, "IOCTL_DISK_SET_PARTITION_INFO_EX"},
    {IOCTL_DISK_GET_DRIVE_LAYOUT_EX, "IOCTL_DISK_GET_DRIVE_LAYOUT_EX"},
    {IOCTL_DISK_SET_DRIVE_LAYOUT_EX, "IOCTL_DISK_SET_DRIVE_LAYOUT_EX"},
    {IOCTL_DISK_CREATE_DISK, "IOCTL_DISK_CREATE_DISK"},
    {IOCTL_DISK_GET_LENGTH_INFO, "IOCTL_DISK_GET_LENGTH_INFO"},
    {IOCTL_DISK_GET_DRIVE_GEOMETRY_EX, "IOCTL_DISK_GET_DRIVE_GEOMETRY_EX"},
    {IOCTL_DISK_REASSIGN_BLOCKS_EX, "IOCTL_DISK_REASSIGN_BLOCKS_EX"},
    {IOCTL_DISK_UPDATE_DRIVE_SIZE, "IOCTL_DISK_UPDATE_DRIVE_SIZE"},
    {IOCTL_DISK_GROW_PARTITION, "IOCTL_DISK_GROW_PARTITION"},
    {IOCTL_DISK_GET_CACHE_INFORMATION, "IOCTL_DISK_GET_CACHE_INFORMATION"},
    {IOCTL_DISK_SET_CACHE_INFORMATION, "IOCTL_DISK_SET_CACHE_INFORMATION"},
    {IOCTL_DISK_DELETE_DRIVE_LAYOUT, "IOCTL_DISK_DELETE_DRIVE_LAYOUT"},
    {IOCTL_DISK_UPDATE_PROPERTIES, "IOCTL_DISK_UPDATE_PROPERTIES"},
    {IOCTL_DISK_RESET_SNAPSHOT_INFO, "IOCTL_DISK_RESET_SNAPSHOT_INFO"},
    {IOCTL_DISK_FORMAT_DRIVE, "IOCTL_DISK_FORMAT_DRIVE"},
    {IOCTL_DISK_SENSE_DEVICE, "IOCTL_DISK_SENSE_DEVICE"},
    {IOCTL_DISK_CHECK_VERIFY, "IOCTL_DISK_CHECK_VERIFY"},
    {IOCTL_DISK_MEDIA_REMOVAL, "IOCTL_DISK_MEDIA_REMOVAL"},
    {IOCTL_DISK_EJECT_MEDIA, "IOCTL_DISK_EJECT_MEDIA"},
    {IOCTL_DISK_LOAD_MEDIA, "IOCTL_DISK_LOAD_MEDIA"},
    {IOCTL_DISK_RESERVE, "IOCTL_DISK_RESERVE"},
    {IOCTL_DISK_RELEASE, "IOCTL_DISK_RELEASE"},
    {IOCTL_DISK_FIND_NEW_DEVICES, "IOCTL_DISK_FIND_NEW_DEVICES"},
    {IOCTL_DISK_GET_MEDIA_TYPES, "IOCTL_DISK_GET_MEDIA_TYPES"},
    {0, NULL},
};

static const flag_repr_t _NtDeviceIoControlFile_IoControlCode_bitmask[] = {
    {0, NULL},
};

static const flag_repr_t _MemoryProtectionFlags_value[] = {
    {0, NULL},
};

static const flag_repr_t _MemoryProtectionFlags_bitmask[] = {
    {PAGE_EXECUTE, "PAGE_EXECUTE"},
    {PAGE_EXECUTE_READ, "PAGE_EXECUTE_READ"},
    {PAGE_EXECUTE_READWRITE, "PAGE_EXECUTE_READWRITE"},
    {PAGE_EXECUTE_WRITECOPY, "PAGE_EXECUTE_WRITECOPY"},
    {PAGE_NOACCESS, "PAGE_NOACCESS"},
    {PAGE_READONLY, "PAGE_READONLY"},
    {PAGE_READWRITE, "PAGE_READWRITE"},
    {PAGE_WRITECOPY, "PAGE_WRITECOPY"},
    {PAGE_GUARD, "PAGE_GUARD"},
    {PAGE_NOCACHE, "PAGE_NOCACHE"},
    {PAGE_WRITECOMBINE, "PAGE_WRITECOMBINE"},
    {0, NULL},
};

static const flag_repr_t _RegEnumValueA_lpType_value[] = {
    {REG_NONE, "REG_NONE"},
    {REG_SZ, "REG_SZ"},
    {REG_EXPAND_SZ, "REG_EXPAND_SZ"},
    {REG_BINARY, "REG_BINARY"},
    {REG_DWORD, "REG_DWORD"},
    {REG_DWORD_BIG_ENDIAN, "REG_DWORD_BIG_ENDIAN"},
    {REG_LINK, "REG_LINK"},
    {REG_MULTI_SZ, "REG_MULTI_SZ"},
    {REG_RESOURCE_LIST, "REG_RESOURCE_LIST"},
    {REG_FULL_RESOURCE_DESCRIPTOR, "REG_FULL_RESOURCE_DESCRIPTOR"},
    {REG_RESOURCE_REQUIREMENTS_LIST, "REG_RESOURCE_REQUIREMENTS_LIST"},
    {REG_QWORD, "REG_QWORD"},
    {0, NULL},
};

static const flag_repr_t _RegEnumValueA_lpType_bitmask[] = {
    {0, NULL},
};

static const flag_repr_t _InternetQueryOptionA_dwOption_value[] = {
    {INTERNET_OPTION_CALLBACK, "INTERNET_OPTION_CALLBACK"},
    {INTERNET_OPTION_CONNECT_TIMEOUT, "INTERNET_OPTION_CONNECT_TIMEOUT"},
    {INTERNET_OPTION_CONNECT_RETRIES, "INTERNET_OPTION_CONNECT_RETRIES"},
    {INTERNET_OPTION_CONNECT_BACKOFF, "INTERNET_OPTION_CONNECT_BACKOFF"},
    {INTERNET_OPTION_SEND_TIMEOUT, "INTERNET_OPTION_SEND_TIMEOUT"},
    {INTERNET_OPTION_CONTROL_SEND_TIMEOUT, "INTERNET_OPTION_CONTROL_SEND_TIMEOUT"},
    {INTERNET_OPTION_RECEIVE_TIMEOUT, "INTERNET_OPTION_RECEIVE_TIMEOUT"},
    {INTERNET_OPTION_CONTROL_RECEIVE_TIMEOUT, "INTERNET_OPTION_CONTROL_RECEIVE_TIMEOUT"},
    {INTERNET_OPTION_DATA_SEND_TIMEOUT, "INTERNET_OPTION_DATA_SEND_TIMEOUT"},
    {INTERNET_OPTION_DATA_RECEIVE_TIMEOUT, "INTERNET_OPTION_DATA_RECEIVE_TIMEOUT"},
    {INTERNET_OPTION_HANDLE_TYPE, "INTERNET_OPTION_HANDLE_TYPE"},
    {INTERNET_OPTION_LISTEN_TIMEOUT, "INTERNET_OPTION_LISTEN_TIMEOUT"},
    {INTERNET_OPTION_READ_BUFFER_SIZE, "INTERNET_OPTION_READ_BUFFER_SIZE"},
    {INTERNET_OPTION_WRITE_BUFFER_SIZE, "INTERNET_OPTION_WRITE_BUFFER_SIZE"},
    {INTERNET_OPTION_ASYNC_ID, "INTERNET_OPTION_ASYNC_ID"},
    {INTERNET_OPTION_ASYNC_PRIORITY, "INTERNET_OPTION_ASYNC_PRIORITY"},
    {INTERNET_OPTION_PARENT_HANDLE, "INTERNET_OPTION_PARENT_HANDLE"},
    {INTERNET_OPTION_KEEP_CONNECTION, "INTERNET_OPTION_KEEP_CONNECTION"},
    {INTERNET_OPTION_REQUEST_FLAGS, "INTERNET_OPTION_REQUEST_FLAGS"},
    {INTERNET_OPTION_EXTENDED_ERROR, "INTERNET_OPTION_EXTENDED_ERROR"},
    {INTERNET_OPTION_OFFLINE_MODE, "INTERNET_OPTION_OFFLINE_MODE"},
    {INTERNET_OPTION_CACHE_STREAM_HANDLE, "INTERNET_OPTION_CACHE_STREAM_HANDLE"},
    {INTERNET_OPTION_USERNAME, "INTERNET_OPTION_USERNAME"},
    {INTERNET_OPTION_PASSWORD, "INTERNET_OPTION_PASSWORD"},
    {INTERNET_OPTION_ASYNC, "INTERNET_OPTION_ASYNC"},
    {INTERNET_OPTION_SECURITY_FLAGS, "INTERNET_OPTION_SECURITY_FLAGS"},
    {INTERNET_OPTION_SECURITY_CERTIFICATE_STRUCT, "INTERNET_OPTION_SECURITY_CERTIFICATE_STRUCT"},
    {INTERNET_OPTION_DATAFILE_NAME, "INTERNET_OPTION_DATAFILE_NAME"},
    {INTERNET_OPTION_URL, "INTERNET_OPTION_URL"},
    {INTERNET_OPTION_SECURITY_CERTIFICATE, "INTERNET_OPTION_SECURITY_CERTIFICATE"},
    {INTERNET_OPTION_SECURITY_KEY_BITNESS, "INTERNET_OPTION_SECURITY_KEY_BITNESS"},
    {INTERNET_OPTION_REFRESH, "INTERNET_OPTION_REFRESH"},
    {INTERNET_OPTION_PROXY, "INTERNET_OPTION_PROXY"},
    {INTERNET_OPTION_SETTINGS_CHANGED, "INTERNET_OPTION_SETTINGS_CHANGED"},
    {INTERNET_OPTION_VERSION, "INTERNET_OPTION_VERSION"},
    {INTERNET_OPTION_USER_AGENT, "INTERNET_OPTION_USER_AGENT"},
    {INTERNET_OPTION_END_BROWSER_SESSION, "INTERNET_OPTION_END_BROWSER_SESSION"},
    {INTERNET_OPTION_PROXY_USERNAME, "INTERNET_OPTION_PROXY_USERNAME"},
    {INTERNET_OPTION_PROXY_PASSWORD, "INTERNET_OPTION_PROXY_PASSWORD"},
    {INTERNET_OPTION_CONTEXT_VALUE, "INTERNET_OPTION_CONTEXT_VALUE"},
    {INTERNET_OPTION_CONNECT_LIMIT, "INTERNET_OPTION_CONNECT_LIMIT"},
    {INTERNET_OPTION_SECURITY_SELECT_CLIENT_CERT, "INTERNET_OPTION_SECURITY_SELECT_CLIENT_CERT"},
    {INTERNET_OPTION_POLICY, "INTERNET_OPTION_POLICY"},
    {INTERNET_OPTION_DISCONNECTED_TIMEOUT, "INTERNET_OPTION_DISCONNECTED_TIMEOUT"},
    {INTERNET_OPTION_CONNECTED_STATE, "INTERNET_OPTION_CONNECTED_STATE"},
    {INTERNET_OPTION_IDLE_STATE, "INTERNET_OPTION_IDLE_STATE"},
    {INTERNET_OPTION_OFFLINE_SEMANTICS, "INTERNET_OPTION_OFFLINE_SEMANTICS"},
    {INTERNET_OPTION_SECONDARY_CACHE_KEY, "INTERNET_OPTION_SECONDARY_CACHE_KEY"},
    {INTERNET_OPTION_CALLBACK_FILTER, "INTERNET_OPTION_CALLBACK_FILTER"},
    {INTERNET_OPTION_CONNECT_TIME, "INTERNET_OPTION_CONNECT_TIME"},
    {INTERNET_OPTION_SEND_THROUGHPUT, "INTERNET_OPTION_SEND_THROUGHPUT"},
    {INTERNET_OPTION_RECEIVE_THROUGHPUT, "INTERNET_OPTION_RECEIVE_THROUGHPUT"},
    {INTERNET_OPTION_REQUEST_PRIORITY, "INTERNET_OPTION_REQUEST_PRIORITY"},
    {INTERNET_OPTION_HTTP_VERSION, "INTERNET_OPTION_HTTP_VERSION"},
    {INTERNET_OPTION_RESET_URLCACHE_SESSION, "INTERNET_OPTION_RESET_URLCACHE_SESSION"},
    {INTERNET_OPTION_ERROR_MASK, "INTERNET_OPTION_ERROR_MASK"},
    {INTERNET_OPTION_FROM_CACHE_TIMEOUT, "INTERNET_OPTION_FROM_CACHE_TIMEOUT"},
    {INTERNET_OPTION_BYPASS_EDITED_ENTRY, "INTERNET_OPTION_BYPASS_EDITED_ENTRY"},
    {INTERNET_OPTION_DIAGNOSTIC_SOCKET_INFO, "INTERNET_OPTION_DIAGNOSTIC_SOCKET_INFO"},
    {INTERNET_OPTION_CODEPAGE, "INTERNET_OPTION_CODEPAGE"},
    {INTERNET_OPTION_CACHE_TIMESTAMPS, "INTERNET_OPTION_CACHE_TIMESTAMPS"},
    {INTERNET_OPTION_DISABLE_AUTODIAL, "INTERNET_OPTION_DISABLE_AUTODIAL"},
    {INTERNET_OPTION_MAX_CONNS_PER_SERVER, "INTERNET_OPTION_MAX_CONNS_PER_SERVER"},
    {INTERNET_OPTION_MAX_CONNS_PER_1_0_SERVER, "INTERNET_OPTION_MAX_CONNS_PER_1_0_SERVER"},
    {INTERNET_OPTION_PER_CONNECTION_OPTION, "INTERNET_OPTION_PER_CONNECTION_OPTION"},
    {INTERNET_OPTION_DIGEST_AUTH_UNLOAD, "INTERNET_OPTION_DIGEST_AUTH_UNLOAD"},
    {INTERNET_OPTION_IGNORE_OFFLINE, "INTERNET_OPTION_IGNORE_OFFLINE"},
    {INTERNET_OPTION_IDENTITY, "INTERNET_OPTION_IDENTITY"},
    {INTERNET_OPTION_REMOVE_IDENTITY, "INTERNET_OPTION_REMOVE_IDENTITY"},
    {INTERNET_OPTION_ALTER_IDENTITY, "INTERNET_OPTION_ALTER_IDENTITY"},
    {INTERNET_OPTION_SUPPRESS_BEHAVIOR, "INTERNET_OPTION_SUPPRESS_BEHAVIOR"},
    {INTERNET_OPTION_AUTODIAL_MODE, "INTERNET_OPTION_AUTODIAL_MODE"},
    {INTERNET_OPTION_AUTODIAL_CONNECTION, "INTERNET_OPTION_AUTODIAL_CONNECTION"},
    {INTERNET_OPTION_CLIENT_CERT_CONTEXT, "INTERNET_OPTION_CLIENT_CERT_CONTEXT"},
    {INTERNET_OPTION_AUTH_FLAGS, "INTERNET_OPTION_AUTH_FLAGS"},
    {INTERNET_OPTION_COOKIES_3RD_PARTY, "INTERNET_OPTION_COOKIES_3RD_PARTY"},
    {INTERNET_OPTION_DISABLE_PASSPORT_AUTH, "INTERNET_OPTION_DISABLE_PASSPORT_AUTH"},
    {INTERNET_OPTION_SEND_UTF8_SERVERNAME_TO_PROXY, "INTERNET_OPTION_SEND_UTF8_SERVERNAME_TO_PROXY"},
    {INTERNET_OPTION_EXEMPT_CONNECTION_LIMIT, "INTERNET_OPTION_EXEMPT_CONNECTION_LIMIT"},
    {INTERNET_OPTION_ENABLE_PASSPORT_AUTH, "INTERNET_OPTION_ENABLE_PASSPORT_AUTH"},
    {INTERNET_OPTION_HIBERNATE_INACTIVE_WORKER_THREADS, "INTERNET_OPTION_HIBERNATE_INACTIVE_WORKER_THREADS"},
    {INTERNET_OPTION_ACTIVATE_WORKER_THREADS, "INTERNET_OPTION_ACTIVATE_WORKER_THREADS"},
    {INTERNET_OPTION_RESTORE_WORKER_THREAD_DEFAULTS, "INTERNET_OPTION_RESTORE_WORKER_THREAD_DEFAULTS"},
    {INTERNET_OPTION_SOCKET_SEND_BUFFER_LENGTH, "INTERNET_OPTION_SOCKET_SEND_BUFFER_LENGTH"},
    {INTERNET_OPTION_PROXY_SETTINGS_CHANGED, "INTERNET_OPTION_PROXY_SETTINGS_CHANGED"},
    {INTERNET_OPTION_DATAFILE_EXT, "INTERNET_OPTION_DATAFILE_EXT"},
    {0, NULL},
};

static const flag_repr_t _InternetQueryOptionA_dwOption_bitmask[] = {
    {0, NULL},
};

static const flag_repr_t _NtAllocateVirtualMemory_AllocationType_value[] = {
    {0, NULL},
};

static const flag_repr_t _NtAllocateVirtualMemory_AllocationType_bitmask[] = {
    {MEM_COMMIT, "MEM_COMMIT"},
    {MEM_RESERVE, "MEM_RESERVE"},
    {MEM_RESET, "MEM_RESET"},
    {MEM_LARGE_PAGES, "MEM_LARGE_PAGES"},
    {MEM_PHYSICAL, "MEM_PHYSICAL"},
    {MEM_TOP_DOWN, "MEM_TOP_DOWN"},
    {MEM_WRITE_WATCH, "MEM_WRITE_WATCH"},
    {0, NULL},
};

static const flag_repr_t _NtProtectVirtualMemory_NewAccessProtection_value[] = {
    {0, NULL},
};

static const flag_repr_t _NtProtectVirtualMemory_NewAccessProtection_bitmask[] = {
    {PAGE_EXECUTE, "PAGE_EXECUTE"},
    {PAGE_EXECUTE_READ, "PAGE_EXECUTE_READ"},
    {PAGE_EXECUTE_READWRITE, "PAGE_EXECUTE_READWRITE"},
    {PAGE_EXECUTE_WRITECOPY, "PAGE_EXECUTE_WRITECOPY"},
    {PAGE_NOACCESS, "PAGE_NOACCESS"},
    {PAGE_READONLY, "PAGE_READONLY"},
    {PAGE_READWRITE, "PAGE_READWRITE"},
    {PAGE_WRITECOPY, "PAGE_WRITECOPY"},
    {PAGE_GUARD, "PAGE_GUARD"},
    {PAGE_NOCACHE, "PAGE_NOCACHE"},
    {PAGE_WRITECOMBINE, "PAGE_WRITECOMBINE"},
    {0, NULL},
};

static const flag_repr_t _InternetSetOptionA_dwOption_value[] = {
    {INTERNET_OPTION_CALLBACK, "INTERNET_OPTION_CALLBACK"},
    {INTERNET_OPTION_CONNECT_TIMEOUT, "INTERNET_OPTION_CONNECT_TIMEOUT"},
    {INTERNET_OPTION_CONNECT_RETRIES, "INTERNET_OPTION_CONNECT_RETRIES"},
    {INTERNET_OPTION_CONNECT_BACKOFF, "INTERNET_OPTION_CONNECT_BACKOFF"},
    {INTERNET_OPTION_SEND_TIMEOUT, "INTERNET_OPTION_SEND_TIMEOUT"},
    {INTERNET_OPTION_CONTROL_SEND_TIMEOUT, "INTERNET_OPTION_CONTROL_SEND_TIMEOUT"},
    {INTERNET_OPTION_RECEIVE_TIMEOUT, "INTERNET_OPTION_RECEIVE_TIMEOUT"},
    {INTERNET_OPTION_CONTROL_RECEIVE_TIMEOUT, "INTERNET_OPTION_CONTROL_RECEIVE_TIMEOUT"},
    {INTERNET_OPTION_DATA_SEND_TIMEOUT, "INTERNET_OPTION_DATA_SEND_TIMEOUT"},
    {INTERNET_OPTION_DATA_RECEIVE_TIMEOUT, "INTERNET_OPTION_DATA_RECEIVE_TIMEOUT"},
    {INTERNET_OPTION_HANDLE_TYPE, "INTERNET_OPTION_HANDLE_TYPE"},
    {INTERNET_OPTION_LISTEN_TIMEOUT, "INTERNET_OPTION_LISTEN_TIMEOUT"},
    {INTERNET_OPTION_READ_BUFFER_SIZE, "INTERNET_OPTION_READ_BUFFER_SIZE"},
    {INTERNET_OPTION_WRITE_BUFFER_SIZE, "INTERNET_OPTION_WRITE_BUFFER_SIZE"},
    {INTERNET_OPTION_ASYNC_ID, "INTERNET_OPTION_ASYNC_ID"},
    {INTERNET_OPTION_ASYNC_PRIORITY, "INTERNET_OPTION_ASYNC_PRIORITY"},
    {INTERNET_OPTION_PARENT_HANDLE, "INTERNET_OPTION_PARENT_HANDLE"},
    {INTERNET_OPTION_KEEP_CONNECTION, "INTERNET_OPTION_KEEP_CONNECTION"},
    {INTERNET_OPTION_REQUEST_FLAGS, "INTERNET_OPTION_REQUEST_FLAGS"},
    {INTERNET_OPTION_EXTENDED_ERROR, "INTERNET_OPTION_EXTENDED_ERROR"},
    {INTERNET_OPTION_OFFLINE_MODE, "INTERNET_OPTION_OFFLINE_MODE"},
    {INTERNET_OPTION_CACHE_STREAM_HANDLE, "INTERNET_OPTION_CACHE_STREAM_HANDLE"},
    {INTERNET_OPTION_USERNAME, "INTERNET_OPTION_USERNAME"},
    {INTERNET_OPTION_PASSWORD, "INTERNET_OPTION_PASSWORD"},
    {INTERNET_OPTION_ASYNC, "INTERNET_OPTION_ASYNC"},
    {INTERNET_OPTION_SECURITY_FLAGS, "INTERNET_OPTION_SECURITY_FLAGS"},
    {INTERNET_OPTION_SECURITY_CERTIFICATE_STRUCT, "INTERNET_OPTION_SECURITY_CERTIFICATE_STRUCT"},
    {INTERNET_OPTION_DATAFILE_NAME, "INTERNET_OPTION_DATAFILE_NAME"},
    {INTERNET_OPTION_URL, "INTERNET_OPTION_URL"},
    {INTERNET_OPTION_SECURITY_CERTIFICATE, "INTERNET_OPTION_SECURITY_CERTIFICATE"},
    {INTERNET_OPTION_SECURITY_KEY_BITNESS, "INTERNET_OPTION_SECURITY_KEY_BITNESS"},
    {INTERNET_OPTION_REFRESH, "INTERNET_OPTION_REFRESH"},
    {INTERNET_OPTION_PROXY, "INTERNET_OPTION_PROXY"},
    {INTERNET_OPTION_SETTINGS_CHANGED, "INTERNET_OPTION_SETTINGS_CHANGED"},
    {INTERNET_OPTION_VERSION, "INTERNET_OPTION_VERSION"},
    {INTERNET_OPTION_USER_AGENT, "INTERNET_OPTION_USER_AGENT"},
    {INTERNET_OPTION_END_BROWSER_SESSION, "INTERNET_OPTION_END_BROWSER_SESSION"},
    {INTERNET_OPTION_PROXY_USERNAME, "INTERNET_OPTION_PROXY_USERNAME"},
    {INTERNET_OPTION_PROXY_PASSWORD, "INTERNET_OPTION_PROXY_PASSWORD"},
    {INTERNET_OPTION_CONTEXT_VALUE, "INTERNET_OPTION_CONTEXT_VALUE"},
    {INTERNET_OPTION_CONNECT_LIMIT, "INTERNET_OPTION_CONNECT_LIMIT"},
    {INTERNET_OPTION_SECURITY_SELECT_CLIENT_CERT, "INTERNET_OPTION_SECURITY_SELECT_CLIENT_CERT"},
    {INTERNET_OPTION_POLICY, "INTERNET_OPTION_POLICY"},
    {INTERNET_OPTION_DISCONNECTED_TIMEOUT, "INTERNET_OPTION_DISCONNECTED_TIMEOUT"},
    {INTERNET_OPTION_CONNECTED_STATE, "INTERNET_OPTION_CONNECTED_STATE"},
    {INTERNET_OPTION_IDLE_STATE, "INTERNET_OPTION_IDLE_STATE"},
    {INTERNET_OPTION_OFFLINE_SEMANTICS, "INTERNET_OPTION_OFFLINE_SEMANTICS"},
    {INTERNET_OPTION_SECONDARY_CACHE_KEY, "INTERNET_OPTION_SECONDARY_CACHE_KEY"},
    {INTERNET_OPTION_CALLBACK_FILTER, "INTERNET_OPTION_CALLBACK_FILTER"},
    {INTERNET_OPTION_CONNECT_TIME, "INTERNET_OPTION_CONNECT_TIME"},
    {INTERNET_OPTION_SEND_THROUGHPUT, "INTERNET_OPTION_SEND_THROUGHPUT"},
    {INTERNET_OPTION_RECEIVE_THROUGHPUT, "INTERNET_OPTION_RECEIVE_THROUGHPUT"},
    {INTERNET_OPTION_REQUEST_PRIORITY, "INTERNET_OPTION_REQUEST_PRIORITY"},
    {INTERNET_OPTION_HTTP_VERSION, "INTERNET_OPTION_HTTP_VERSION"},
    {INTERNET_OPTION_RESET_URLCACHE_SESSION, "INTERNET_OPTION_RESET_URLCACHE_SESSION"},
    {INTERNET_OPTION_ERROR_MASK, "INTERNET_OPTION_ERROR_MASK"},
    {INTERNET_OPTION_FROM_CACHE_TIMEOUT, "INTERNET_OPTION_FROM_CACHE_TIMEOUT"},
    {INTERNET_OPTION_BYPASS_EDITED_ENTRY, "INTERNET_OPTION_BYPASS_EDITED_ENTRY"},
    {INTERNET_OPTION_DIAGNOSTIC_SOCKET_INFO, "INTERNET_OPTION_DIAGNOSTIC_SOCKET_INFO"},
    {INTERNET_OPTION_CODEPAGE, "INTERNET_OPTION_CODEPAGE"},
    {INTERNET_OPTION_CACHE_TIMESTAMPS, "INTERNET_OPTION_CACHE_TIMESTAMPS"},
    {INTERNET_OPTION_DISABLE_AUTODIAL, "INTERNET_OPTION_DISABLE_AUTODIAL"},
    {INTERNET_OPTION_MAX_CONNS_PER_SERVER, "INTERNET_OPTION_MAX_CONNS_PER_SERVER"},
    {INTERNET_OPTION_MAX_CONNS_PER_1_0_SERVER, "INTERNET_OPTION_MAX_CONNS_PER_1_0_SERVER"},
    {INTERNET_OPTION_PER_CONNECTION_OPTION, "INTERNET_OPTION_PER_CONNECTION_OPTION"},
    {INTERNET_OPTION_DIGEST_AUTH_UNLOAD, "INTERNET_OPTION_DIGEST_AUTH_UNLOAD"},
    {INTERNET_OPTION_IGNORE_OFFLINE, "INTERNET_OPTION_IGNORE_OFFLINE"},
    {INTERNET_OPTION_IDENTITY, "INTERNET_OPTION_IDENTITY"},
    {INTERNET_OPTION_REMOVE_IDENTITY, "INTERNET_OPTION_REMOVE_IDENTITY"},
    {INTERNET_OPTION_ALTER_IDENTITY, "INTERNET_OPTION_ALTER_IDENTITY"},
    {INTERNET_OPTION_SUPPRESS_BEHAVIOR, "INTERNET_OPTION_SUPPRESS_BEHAVIOR"},
    {INTERNET_OPTION_AUTODIAL_MODE, "INTERNET_OPTION_AUTODIAL_MODE"},
    {INTERNET_OPTION_AUTODIAL_CONNECTION, "INTERNET_OPTION_AUTODIAL_CONNECTION"},
    {INTERNET_OPTION_CLIENT_CERT_CONTEXT, "INTERNET_OPTION_CLIENT_CERT_CONTEXT"},
    {INTERNET_OPTION_AUTH_FLAGS, "INTERNET_OPTION_AUTH_FLAGS"},
    {INTERNET_OPTION_COOKIES_3RD_PARTY, "INTERNET_OPTION_COOKIES_3RD_PARTY"},
    {INTERNET_OPTION_DISABLE_PASSPORT_AUTH, "INTERNET_OPTION_DISABLE_PASSPORT_AUTH"},
    {INTERNET_OPTION_SEND_UTF8_SERVERNAME_TO_PROXY, "INTERNET_OPTION_SEND_UTF8_SERVERNAME_TO_PROXY"},
    {INTERNET_OPTION_EXEMPT_CONNECTION_LIMIT, "INTERNET_OPTION_EXEMPT_CONNECTION_LIMIT"},
    {INTERNET_OPTION_ENABLE_PASSPORT_AUTH, "INTERNET_OPTION_ENABLE_PASSPORT_AUTH"},
    {INTERNET_OPTION_HIBERNATE_INACTIVE_WORKER_THREADS, "INTERNET_OPTION_HIBERNATE_INACTIVE_WORKER_THREADS"},
    {INTERNET_OPTION_ACTIVATE_WORKER_THREADS, "INTERNET_OPTION_ACTIVATE_WORKER_THREADS"},
    {INTERNET_OPTION_RESTORE_WORKER_THREAD_DEFAULTS, "INTERNET_OPTION_RESTORE_WORKER_THREAD_DEFAULTS"},
    {INTERNET_OPTION_SOCKET_SEND_BUFFER_LENGTH, "INTERNET_OPTION_SOCKET_SEND_BUFFER_LENGTH"},
    {INTERNET_OPTION_PROXY_SETTINGS_CHANGED, "INTERNET_OPTION_PROXY_SETTINGS_CHANGED"},
    {INTERNET_OPTION_DATAFILE_EXT, "INTERNET_OPTION_DATAFILE_EXT"},
    {0, NULL},
};

static const flag_repr_t _InternetSetOptionA_dwOption_bitmask[] = {
    {0, NULL},
};

static const flag_repr_t _NtCreateFile_CreateDisposition_value[] = {
    {FILE_SUPERSEDE, "FILE_SUPERSEDE"},
    {FILE_CREATE, "FILE_CREATE"},
    {FILE_OPEN, "FILE_OPEN"},
    {FILE_OPEN_IF, "FILE_OPEN_IF"},
    {FILE_OVERWRITE, "FILE_OVERWRITE"},
    {FILE_OVERWRITE_IF, "FILE_OVERWRITE_IF"},
    {0, NULL},
};

static const flag_repr_t _NtCreateFile_CreateDisposition_bitmask[] = {
    {0, NULL},
};

static const flag_repr_t _PRIORITY_CLASS_value[] = {
    {0, NULL},
};

static const flag_repr_t _PRIORITY_CLASS_bitmask[] = {
    {ABOVE_NORMAL_PRIORITY_CLASS, "ABOVE_NORMAL_PRIORITY_CLASS"},
    {BELOW_NORMAL_PRIORITY_CLASS, "BELOW_NORMAL_PRIORITY_CLASS"},
    {HIGH_PRIORITY_CLASS, "HIGH_PRIORITY_CLASS"},
    {IDLE_PRIORITY_CLASS, "IDLE_PRIORITY_CLASS"},
    {NORMAL_PRIORITY_CLASS, "NORMAL_PRIORITY_CLASS"},
    {REALTIME_PRIORITY_CLASS, "REALTIME_PRIORITY_CLASS"},
    {0, NULL},
};

static const flag_repr_t _NtOpenFile_ShareAccess_value[] = {
    {0, NULL},
};

static const flag_repr_t _NtOpenFile_ShareAccess_bitmask[] = {
    {FILE_SHARE_READ, "FILE_SHARE_READ"},
    {FILE_SHARE_WRITE, "FILE_SHARE_WRITE"},
    {FILE_SHARE_DELETE, "FILE_SHARE_DELETE"},
    {0, NULL},
};

static const flag_repr_t _AllocationType_value[] = {
    {0, NULL},
};

static const flag_repr_t _AllocationType_bitmask[] = {
    {MEM_COMMIT, "MEM_COMMIT"},
    {MEM_RESERVE, "MEM_RESERVE"},
    {MEM_RESET, "MEM_RESET"},
    {MEM_LARGE_PAGES, "MEM_LARGE_PAGES"},
    {MEM_PHYSICAL, "MEM_PHYSICAL"},
    {MEM_TOP_DOWN, "MEM_TOP_DOWN"},
    {MEM_WRITE_WATCH, "MEM_WRITE_WATCH"},
    {0, NULL},
};

static const flag_repr_t _WindowStyles_value[] = {
    {WS_OVERLAPPEDWINDOW, "WS_OVERLAPPEDWINDOW"},
    {WS_POPUPWINDOW, "WS_POPUPWINDOW"},
    {0, NULL},
};

static const flag_repr_t _WindowStyles_bitmask[] = {
    {WS_OVERLAPPED, "WS_OVERLAPPED"},
    {WS_POPUP, "WS_POPUP"},
    {WS_CHILD, "WS_CHILD"},
    {WS_MINIMIZE, "WS_MINIMIZE"},
    {WS_VISIBLE, "WS_VISIBLE"},
    {WS_DISABLED, "WS_DISABLED"},
    {WS_CLIPSIBLINGS, "WS_CLIPSIBLINGS"},
    {WS_CLIPCHILDREN, "WS_CLIPCHILDREN"},
    {WS_MAXIMIZE, "WS_MAXIMIZE"},
    {WS_CAPTION, "WS_CAPTION"},
    {WS_BORDER, "WS_BORDER"},
    {WS_DLGFRAME, "WS_DLGFRAME"},
    {WS_VSCROLL, "WS_VSCROLL"},
    {WS_HSCROLL, "WS_HSCROLL"},
    {WS_SYSMENU, "WS_SYSMENU"},
    {WS_THICKFRAME, "WS_THICKFRAME"},
    {WS_GROUP, "WS_GROUP"},
    {WS_TABSTOP, "WS_TABSTOP"},
    {WS_MINIMIZEBOX, "WS_MINIMIZEBOX"},
    {WS_MAXIMIZEBOX, "WS_MAXIMIZEBOX"},
    {0, NULL},
};

static const flag_repr_t _SetErrorMode_uMode_value[] = {
    {0, NULL},
};

static const flag_repr_t _SetErrorMode_uMode_bitmask[] = {
    {SEM_FAILCRITICALERRORS, "SEM_FAILCRITICALERRORS"},
    {SEM_NOALIGNMENTFAULTEXCEPT, "SEM_NOALIGNMENTFAULTEXCEPT"},
    {SEM_NOGPFAULTERRORBOX, "SEM_NOGPFAULTERRORBOX"},
    {SEM_NOOPENFILEERRORBOX, "SEM_NOOPENFILEERRORBOX"},
    {0, NULL},
};

static const flag_repr_t _RegSetValueExW_dwType_value[] = {
    {REG_NONE, "REG_NONE"},
    {REG_SZ, "REG_SZ"},
    {REG_EXPAND_SZ, "REG_EXPAND_SZ"},
    {REG_BINARY, "REG_BINARY"},
    {REG_DWORD, "REG_DWORD"},
    {REG_DWORD_BIG_ENDIAN, "REG_DWORD_BIG_ENDIAN"},
    {REG_LINK, "REG_LINK"},
    {REG_MULTI_SZ, "REG_MULTI_SZ"},
    {REG_RESOURCE_LIST, "REG_RESOURCE_LIST"},
    {REG_FULL_RESOURCE_DESCRIPTOR, "REG_FULL_RESOURCE_DESCRIPTOR"},
    {REG_RESOURCE_REQUIREMENTS_LIST, "REG_RESOURCE_REQUIREMENTS_LIST"},
    {REG_QWORD, "REG_QWORD"},
    {0, NULL},
};

static const flag_repr_t _RegSetValueExW_dwType_bitmask[] = {
    {0, NULL},
};

static const flag_repr_t _CreateWindowExA_dwExStyle_value[] = {
    {WS_EX_OVERLAPPEDWINDOW, "WS_EX_OVERLAPPEDWINDOW"},
    {WS_EX_PALETTEWINDOW, "WS_EX_PALETTEWINDOW"},
    {0, NULL},
};

static const flag_repr_t _CreateWindowExA_dwExStyle_bitmask[] = {
    {WS_EX_DLGMODALFRAME, "WS_EX_DLGMODALFRAME"},
    {WS_EX_NOPARENTNOTIFY, "WS_EX_NOPARENTNOTIFY"},
    {WS_EX_TOPMOST, "WS_EX_TOPMOST"},
    {WS_EX_ACCEPTFILES, "WS_EX_ACCEPTFILES"},
    {WS_EX_TRANSPARENT, "WS_EX_TRANSPARENT"},
    {WS_EX_MDICHILD, "WS_EX_MDICHILD"},
    {WS_EX_TOOLWINDOW, "WS_EX_TOOLWINDOW"},
    {WS_EX_WINDOWEDGE, "WS_EX_WINDOWEDGE"},
    {WS_EX_CLIENTEDGE, "WS_EX_CLIENTEDGE"},
    {WS_EX_CONTEXTHELP, "WS_EX_CONTEXTHELP"},
    {WS_EX_RIGHT, "WS_EX_RIGHT"},
    {WS_EX_LEFT, "WS_EX_LEFT"},
    {WS_EX_RTLREADING, "WS_EX_RTLREADING"},
    {WS_EX_LTRREADING, "WS_EX_LTRREADING"},
    {WS_EX_LEFTSCROLLBAR, "WS_EX_LEFTSCROLLBAR"},
    {WS_EX_RIGHTSCROLLBAR, "WS_EX_RIGHTSCROLLBAR"},
    {WS_EX_CONTROLPARENT, "WS_EX_CONTROLPARENT"},
    {WS_EX_STATICEDGE, "WS_EX_STATICEDGE"},
    {WS_EX_APPWINDOW, "WS_EX_APPWINDOW"},
    {WS_EX_LAYERED, "WS_EX_LAYERED"},
    {WS_EX_NOINHERITLAYOUT, "WS_EX_NOINHERITLAYOUT"},
    {WS_EX_LAYOUTRTL, "WS_EX_LAYOUTRTL"},
    {WS_EX_COMPOSITED, "WS_EX_COMPOSITED"},
    {WS_EX_NOACTIVATE, "WS_EX_NOACTIVATE"},
    {0, NULL},
};

static const flag_repr_t _ExtendedWindowStyles_value[] = {
    {WS_EX_OVERLAPPEDWINDOW, "WS_EX_OVERLAPPEDWINDOW"},
    {WS_EX_PALETTEWINDOW, "WS_EX_PALETTEWINDOW"},
    {0, NULL},
};

static const flag_repr_t _ExtendedWindowStyles_bitmask[] = {
    {WS_EX_DLGMODALFRAME, "WS_EX_DLGMODALFRAME"},
    {WS_EX_NOPARENTNOTIFY, "WS_EX_NOPARENTNOTIFY"},
    {WS_EX_TOPMOST, "WS_EX_TOPMOST"},
    {WS_EX_ACCEPTFILES, "WS_EX_ACCEPTFILES"},
    {WS_EX_TRANSPARENT, "WS_EX_TRANSPARENT"},
    {WS_EX_MDICHILD, "WS_EX_MDICHILD"},
    {WS_EX_TOOLWINDOW, "WS_EX_TOOLWINDOW"},
    {WS_EX_WINDOWEDGE, "WS_EX_WINDOWEDGE"},
    {WS_EX_CLIENTEDGE, "WS_EX_CLIENTEDGE"},
    {WS_EX_CONTEXTHELP, "WS_EX_CONTEXTHELP"},
    {WS_EX_RIGHT, "WS_EX_RIGHT"},
    {WS_EX_LEFT, "WS_EX_LEFT"},
    {WS_EX_RTLREADING, "WS_EX_RTLREADING"},
    {WS_EX_LTRREADING, "WS_EX_LTRREADING"},
    {WS_EX_LEFTSCROLLBAR, "WS_EX_LEFTSCROLLBAR"},
    {WS_EX_RIGHTSCROLLBAR, "WS_EX_RIGHTSCROLLBAR"},
    {WS_EX_CONTROLPARENT, "WS_EX_CONTROLPARENT"},
    {WS_EX_STATICEDGE, "WS_EX_STATICEDGE"},
    {WS_EX_APPWINDOW, "WS_EX_APPWINDOW"},
    {WS_EX_LAYERED, "WS_EX_LAYERED"},
    {WS_EX_NOINHERITLAYOUT, "WS_EX_NOINHERITLAYOUT"},
    {WS_EX_LAYOUTRTL, "WS_EX_LAYOUTRTL"},
    {WS_EX_COMPOSITED, "WS_EX_COMPOSITED"},
    {WS_EX_NOACTIVATE, "WS_EX_NOACTIVATE"},
    {0, NULL},
};

static const flag_repr_t _NtCreateFile_ShareAccess_value[] = {
    {0, NULL},
};

static const flag_repr_t _NtCreateFile_ShareAccess_bitmask[] = {
    {FILE_SHARE_READ, "FILE_SHARE_READ"},
    {FILE_SHARE_WRITE, "FILE_SHARE_WRITE"},
    {FILE_SHARE_DELETE, "FILE_SHARE_DELETE"},
    {0, NULL},
};

static const flag_repr_t _ShareAccessFlags_value[] = {
    {0, NULL},
};

static const flag_repr_t _ShareAccessFlags_bitmask[] = {
    {FILE_SHARE_READ, "FILE_SHARE_READ"},
    {FILE_SHARE_WRITE, "FILE_SHARE_WRITE"},
    {FILE_SHARE_DELETE, "FILE_SHARE_DELETE"},
    {0, NULL},
};

static const flag_repr_t _RegEnumValueW_lpType_value[] = {
    {REG_NONE, "REG_NONE"},
    {REG_SZ, "REG_SZ"},
    {REG_EXPAND_SZ, "REG_EXPAND_SZ"},
    {REG_BINARY, "REG_BINARY"},
    {REG_DWORD, "REG_DWORD"},
    {REG_DWORD_BIG_ENDIAN, "REG_DWORD_BIG_ENDIAN"},
    {REG_LINK, "REG_LINK"},
    {REG_MULTI_SZ, "REG_MULTI_SZ"},
    {REG_RESOURCE_LIST, "REG_RESOURCE_LIST"},
    {REG_FULL_RESOURCE_DESCRIPTOR, "REG_FULL_RESOURCE_DESCRIPTOR"},
    {REG_RESOURCE_REQUIREMENTS_LIST, "REG_RESOURCE_REQUIREMENTS_LIST"},
    {REG_QWORD, "REG_QWORD"},
    {0, NULL},
};

static const flag_repr_t _RegEnumValueW_lpType_bitmask[] = {
    {0, NULL},
};

static const flag_repr_t _WINDOWS_HOOKS_value[] = {
    {WH_JOURNALRECORD, "WH_JOURNALRECORD"},
    {WH_JOURNALPLAYBACK, "WH_JOURNALPLAYBACK"},
    {WH_KEYBOARD, "WH_KEYBOARD"},
    {WH_GETMESSAGE, "WH_GETMESSAGE"},
    {WH_CALLWNDPROC, "WH_CALLWNDPROC"},
    {WH_CBT, "WH_CBT"},
    {WH_SYSMSGFILTER, "WH_SYSMSGFILTER"},
    {WH_MOUSE, "WH_MOUSE"},
    {WH_HARDWARE, "WH_HARDWARE"},
    {WH_DEBUG, "WH_DEBUG"},
    {WH_SHELL, "WH_SHELL"},
    {WH_FOREGROUNDIDLE, "WH_FOREGROUNDIDLE"},
    {WH_CALLWNDPROCRET, "WH_CALLWNDPROCRET"},
    {WH_KEYBOARD_LL, "WH_KEYBOARD_LL"},
    {WH_MOUSE_LL, "WH_MOUSE_LL"},
    {0, NULL},
};

static const flag_repr_t _WINDOWS_HOOKS_bitmask[] = {
    {0, NULL},
};

static const flag_repr_t _SHGetFolderPathW_nFolder_value[] = {
    {CSIDL_ADMINTOOLS, "CSIDL_ADMINTOOLS"},
    {CSIDL_ALTSTARTUP, "CSIDL_ALTSTARTUP"},
    {CSIDL_APPDATA, "CSIDL_APPDATA"},
    {CSIDL_BITBUCKET, "CSIDL_BITBUCKET"},
    {CSIDL_CDBURN_AREA, "CSIDL_CDBURN_AREA"},
    {CSIDL_COMMON_ADMINTOOLS, "CSIDL_COMMON_ADMINTOOLS"},
    {CSIDL_COMMON_ALTSTARTUP, "CSIDL_COMMON_ALTSTARTUP"},
    {CSIDL_COMMON_APPDATA, "CSIDL_COMMON_APPDATA"},
    {CSIDL_COMMON_DESKTOPDIRECTORY, "CSIDL_COMMON_DESKTOPDIRECTORY"},
    {CSIDL_COMMON_DOCUMENTS, "CSIDL_COMMON_DOCUMENTS"},
    {CSIDL_COMMON_FAVORITES, "CSIDL_COMMON_FAVORITES"},
    {CSIDL_COMMON_MUSIC, "CSIDL_COMMON_MUSIC"},
    {CSIDL_COMMON_OEM_LINKS, "CSIDL_COMMON_OEM_LINKS"},
    {CSIDL_COMMON_PICTURES, "CSIDL_COMMON_PICTURES"},
    {CSIDL_COMMON_PROGRAMS, "CSIDL_COMMON_PROGRAMS"},
    {CSIDL_COMMON_STARTMENU, "CSIDL_COMMON_STARTMENU"},
    {CSIDL_COMMON_STARTUP, "CSIDL_COMMON_STARTUP"},
    {CSIDL_COMMON_TEMPLATES, "CSIDL_COMMON_TEMPLATES"},
    {CSIDL_COMMON_VIDEO, "CSIDL_COMMON_VIDEO"},
    {CSIDL_COMPUTERSNEARME, "CSIDL_COMPUTERSNEARME"},
    {CSIDL_CONNECTIONS, "CSIDL_CONNECTIONS"},
    {CSIDL_CONTROLS, "CSIDL_CONTROLS"},
    {CSIDL_COOKIES, "CSIDL_COOKIES"},
    {CSIDL_DESKTOP, "CSIDL_DESKTOP"},
    {CSIDL_DESKTOPDIRECTORY, "CSIDL_DESKTOPDIRECTORY"},
    {CSIDL_DRIVES, "CSIDL_DRIVES"},
    {CSIDL_FAVORITES, "CSIDL_FAVORITES"},
    {CSIDL_FONTS, "CSIDL_FONTS"},
    {CSIDL_HISTORY, "CSIDL_HISTORY"},
    {CSIDL_INTERNET, "CSIDL_INTERNET"},
    {CSIDL_INTERNET_CACHE, "CSIDL_INTERNET_CACHE"},
    {CSIDL_LOCAL_APPDATA, "CSIDL_LOCAL_APPDATA"},
    {CSIDL_MYDOCUMENTS, "CSIDL_MYDOCUMENTS"},
    {CSIDL_MYMUSIC, "CSIDL_MYMUSIC"},
    {CSIDL_MYPICTURES, "CSIDL_MYPICTURES"},
    {CSIDL_MYVIDEO, "CSIDL_MYVIDEO"},
    {CSIDL_NETHOOD, "CSIDL_NETHOOD"},
    {CSIDL_NETWORK, "CSIDL_NETWORK"},
    {CSIDL_PERSONAL, "CSIDL_PERSONAL"},
    {CSIDL_PRINTERS, "CSIDL_PRINTERS"},
    {CSIDL_PRINTHOOD, "CSIDL_PRINTHOOD"},
    {CSIDL_PROFILE, "CSIDL_PROFILE"},
    {CSIDL_PROGRAM_FILES, "CSIDL_PROGRAM_FILES"},
    {CSIDL_PROGRAM_FILESX86, "CSIDL_PROGRAM_FILESX86"},
    {CSIDL_PROGRAM_FILES_COMMON, "CSIDL_PROGRAM_FILES_COMMON"},
    {CSIDL_PROGRAM_FILES_COMMONX86, "CSIDL_PROGRAM_FILES_COMMONX86"},
    {CSIDL_PROGRAMS, "CSIDL_PROGRAMS"},
    {CSIDL_RECENT, "CSIDL_RECENT"},
    {CSIDL_RESOURCES, "CSIDL_RESOURCES"},
    {CSIDL_RESOURCES_LOCALIZED, "CSIDL_RESOURCES_LOCALIZED"},
    {CSIDL_SENDTO, "CSIDL_SENDTO"},
    {CSIDL_STARTMENU, "CSIDL_STARTMENU"},
    {CSIDL_STARTUP, "CSIDL_STARTUP"},
    {CSIDL_SYSTEM, "CSIDL_SYSTEM"},
    {CSIDL_SYSTEMX86, "CSIDL_SYSTEMX86"},
    {CSIDL_TEMPLATES, "CSIDL_TEMPLATES"},
    {CSIDL_WINDOWS, "CSIDL_WINDOWS"},
    {0, NULL},
};

static const flag_repr_t _SHGetFolderPathW_nFolder_bitmask[] = {
    {0, NULL},
};

static const flag_repr_t _SetWindowsHookExW_idHook_value[] = {
    {WH_JOURNALRECORD, "WH_JOURNALRECORD"},
    {WH_JOURNALPLAYBACK, "WH_JOURNALPLAYBACK"},
    {WH_KEYBOARD, "WH_KEYBOARD"},
    {WH_GETMESSAGE, "WH_GETMESSAGE"},
    {WH_CALLWNDPROC, "WH_CALLWNDPROC"},
    {WH_CBT, "WH_CBT"},
    {WH_SYSMSGFILTER, "WH_SYSMSGFILTER"},
    {WH_MOUSE, "WH_MOUSE"},
    {WH_HARDWARE, "WH_HARDWARE"},
    {WH_DEBUG, "WH_DEBUG"},
    {WH_SHELL, "WH_SHELL"},
    {WH_FOREGROUNDIDLE, "WH_FOREGROUNDIDLE"},
    {WH_CALLWNDPROCRET, "WH_CALLWNDPROCRET"},
    {WH_KEYBOARD_LL, "WH_KEYBOARD_LL"},
    {WH_MOUSE_LL, "WH_MOUSE_LL"},
    {0, NULL},
};

static const flag_repr_t _SetWindowsHookExW_idHook_bitmask[] = {
    {0, NULL},
};

static const flag_repr_t _DeviceIoControl_dwIoControlCode_value[] = {
    {IOCTL_STORAGE_CHECK_VERIFY, "IOCTL_STORAGE_CHECK_VERIFY"},
    {IOCTL_STORAGE_CHECK_VERIFY2, "IOCTL_STORAGE_CHECK_VERIFY2"},
    {IOCTL_STORAGE_MEDIA_REMOVAL, "IOCTL_STORAGE_MEDIA_REMOVAL"},
    {IOCTL_STORAGE_EJECT_MEDIA, "IOCTL_STORAGE_EJECT_MEDIA"},
    {IOCTL_STORAGE_LOAD_MEDIA, "IOCTL_STORAGE_LOAD_MEDIA"},
    {IOCTL_STORAGE_LOAD_MEDIA2, "IOCTL_STORAGE_LOAD_MEDIA2"},
    {IOCTL_STORAGE_RESERVE, "IOCTL_STORAGE_RESERVE"},
    {IOCTL_STORAGE_RELEASE, "IOCTL_STORAGE_RELEASE"},
    {IOCTL_STORAGE_FIND_NEW_DEVICES, "IOCTL_STORAGE_FIND_NEW_DEVICES"},
    {IOCTL_STORAGE_EJECTION_CONTROL, "IOCTL_STORAGE_EJECTION_CONTROL"},
    {IOCTL_STORAGE_MCN_CONTROL, "IOCTL_STORAGE_MCN_CONTROL"},
    {IOCTL_STORAGE_GET_MEDIA_TYPES, "IOCTL_STORAGE_GET_MEDIA_TYPES"},
    {IOCTL_STORAGE_GET_MEDIA_TYPES_EX, "IOCTL_STORAGE_GET_MEDIA_TYPES_EX"},
    {IOCTL_STORAGE_GET_MEDIA_SERIAL_NUMBER, "IOCTL_STORAGE_GET_MEDIA_SERIAL_NUMBER"},
    {IOCTL_STORAGE_GET_HOTPLUG_INFO, "IOCTL_STORAGE_GET_HOTPLUG_INFO"},
    {IOCTL_STORAGE_SET_HOTPLUG_INFO, "IOCTL_STORAGE_SET_HOTPLUG_INFO"},
    {IOCTL_STORAGE_RESET_BUS, "IOCTL_STORAGE_RESET_BUS"},
    {IOCTL_STORAGE_RESET_DEVICE, "IOCTL_STORAGE_RESET_DEVICE"},
    {IOCTL_STORAGE_BREAK_RESERVATION, "IOCTL_STORAGE_BREAK_RESERVATION"},
    {IOCTL_STORAGE_GET_DEVICE_NUMBER, "IOCTL_STORAGE_GET_DEVICE_NUMBER"},
    {IOCTL_STORAGE_PREDICT_FAILURE, "IOCTL_STORAGE_PREDICT_FAILURE"},
    {IOCTL_STORAGE_READ_CAPACITY, "IOCTL_STORAGE_READ_CAPACITY"},
    {IOCTL_DISK_GET_DRIVE_GEOMETRY, "IOCTL_DISK_GET_DRIVE_GEOMETRY"},
    {IOCTL_DISK_GET_PARTITION_INFO, "IOCTL_DISK_GET_PARTITION_INFO"},
    {IOCTL_DISK_SET_PARTITION_INFO, "IOCTL_DISK_SET_PARTITION_INFO"},
    {IOCTL_DISK_GET_DRIVE_LAYOUT, "IOCTL_DISK_GET_DRIVE_LAYOUT"},
    {IOCTL_DISK_SET_DRIVE_LAYOUT, "IOCTL_DISK_SET_DRIVE_LAYOUT"},
    {IOCTL_DISK_VERIFY, "IOCTL_DISK_VERIFY"},
    {IOCTL_DISK_FORMAT_TRACKS, "IOCTL_DISK_FORMAT_TRACKS"},
    {IOCTL_DISK_REASSIGN_BLOCKS, "IOCTL_DISK_REASSIGN_BLOCKS"},
    {IOCTL_DISK_PERFORMANCE, "IOCTL_DISK_PERFORMANCE"},
    {IOCTL_DISK_IS_WRITABLE, "IOCTL_DISK_IS_WRITABLE"},
    {IOCTL_DISK_LOGGING, "IOCTL_DISK_LOGGING"},
    {IOCTL_DISK_FORMAT_TRACKS_EX, "IOCTL_DISK_FORMAT_TRACKS_EX"},
    {IOCTL_DISK_HISTOGRAM_STRUCTURE, "IOCTL_DISK_HISTOGRAM_STRUCTURE"},
    {IOCTL_DISK_HISTOGRAM_DATA, "IOCTL_DISK_HISTOGRAM_DATA"},
    {IOCTL_DISK_HISTOGRAM_RESET, "IOCTL_DISK_HISTOGRAM_RESET"},
    {IOCTL_DISK_REQUEST_STRUCTURE, "IOCTL_DISK_REQUEST_STRUCTURE"},
    {IOCTL_DISK_REQUEST_DATA, "IOCTL_DISK_REQUEST_DATA"},
    {IOCTL_DISK_PERFORMANCE_OFF, "IOCTL_DISK_PERFORMANCE_OFF"},
    {IOCTL_DISK_CONTROLLER_NUMBER, "IOCTL_DISK_CONTROLLER_NUMBER"},
    {IOCTL_DISK_GET_PARTITION_INFO_EX, "IOCTL_DISK_GET_PARTITION_INFO_EX"},
    {IOCTL_DISK_SET_PARTITION_INFO_EX, "IOCTL_DISK_SET_PARTITION_INFO_EX"},
    {IOCTL_DISK_GET_DRIVE_LAYOUT_EX, "IOCTL_DISK_GET_DRIVE_LAYOUT_EX"},
    {IOCTL_DISK_SET_DRIVE_LAYOUT_EX, "IOCTL_DISK_SET_DRIVE_LAYOUT_EX"},
    {IOCTL_DISK_CREATE_DISK, "IOCTL_DISK_CREATE_DISK"},
    {IOCTL_DISK_GET_LENGTH_INFO, "IOCTL_DISK_GET_LENGTH_INFO"},
    {IOCTL_DISK_GET_DRIVE_GEOMETRY_EX, "IOCTL_DISK_GET_DRIVE_GEOMETRY_EX"},
    {IOCTL_DISK_REASSIGN_BLOCKS_EX, "IOCTL_DISK_REASSIGN_BLOCKS_EX"},
    {IOCTL_DISK_UPDATE_DRIVE_SIZE, "IOCTL_DISK_UPDATE_DRIVE_SIZE"},
    {IOCTL_DISK_GROW_PARTITION, "IOCTL_DISK_GROW_PARTITION"},
    {IOCTL_DISK_GET_CACHE_INFORMATION, "IOCTL_DISK_GET_CACHE_INFORMATION"},
    {IOCTL_DISK_SET_CACHE_INFORMATION, "IOCTL_DISK_SET_CACHE_INFORMATION"},
    {IOCTL_DISK_DELETE_DRIVE_LAYOUT, "IOCTL_DISK_DELETE_DRIVE_LAYOUT"},
    {IOCTL_DISK_UPDATE_PROPERTIES, "IOCTL_DISK_UPDATE_PROPERTIES"},
    {IOCTL_DISK_RESET_SNAPSHOT_INFO, "IOCTL_DISK_RESET_SNAPSHOT_INFO"},
    {IOCTL_DISK_FORMAT_DRIVE, "IOCTL_DISK_FORMAT_DRIVE"},
    {IOCTL_DISK_SENSE_DEVICE, "IOCTL_DISK_SENSE_DEVICE"},
    {IOCTL_DISK_CHECK_VERIFY, "IOCTL_DISK_CHECK_VERIFY"},
    {IOCTL_DISK_MEDIA_REMOVAL, "IOCTL_DISK_MEDIA_REMOVAL"},
    {IOCTL_DISK_EJECT_MEDIA, "IOCTL_DISK_EJECT_MEDIA"},
    {IOCTL_DISK_LOAD_MEDIA, "IOCTL_DISK_LOAD_MEDIA"},
    {IOCTL_DISK_RESERVE, "IOCTL_DISK_RESERVE"},
    {IOCTL_DISK_RELEASE, "IOCTL_DISK_RELEASE"},
    {IOCTL_DISK_FIND_NEW_DEVICES, "IOCTL_DISK_FIND_NEW_DEVICES"},
    {IOCTL_DISK_GET_MEDIA_TYPES, "IOCTL_DISK_GET_MEDIA_TYPES"},
    {0, NULL},
};

static const flag_repr_t _DeviceIoControl_dwIoControlCode_bitmask[] = {
    {0, NULL},
};

static const flag_repr_t _ACCESS_MASK_value[] = {
    {0, NULL},
};

static const flag_repr_t _ACCESS_MASK_bitmask[] = {
    {STANDARD_RIGHTS_ALL, "STANDARD_RIGHTS_ALL"},
    {STANDARD_RIGHTS_REQUIRED, "STANDARD_RIGHTS_REQUIRED"},
    {DELETE, "DELETE"},
    {READ_CONTROL, "READ_CONTROL"},
    {WRITE_DAC, "WRITE_DAC"},
    {WRITE_OWNER, "WRITE_OWNER"},
    {SYNCHRONIZE, "SYNCHRONIZE"},
    {SPECIFIC_RIGHTS_ALL, "SPECIFIC_RIGHTS_ALL"},
    {ACCESS_SYSTEM_SECURITY, "ACCESS_SYSTEM_SECURITY"},
    {MAXIMUM_ALLOWED, "MAXIMUM_ALLOWED"},
    {GENERIC_READ, "GENERIC_READ"},
    {GENERIC_WRITE, "GENERIC_WRITE"},
    {GENERIC_EXECUTE, "GENERIC_EXECUTE"},
    {GENERIC_ALL, "GENERIC_ALL"},
    {0, NULL},
};

static const flag_repr_t _NtSetValueKey_Type_value[] = {
    {REG_NONE, "REG_NONE"},
    {REG_SZ, "REG_SZ"},
    {REG_EXPAND_SZ, "REG_EXPAND_SZ"},
    {REG_BINARY, "REG_BINARY"},
    {REG_DWORD, "REG_DWORD"},
    {REG_DWORD_BIG_ENDIAN, "REG_DWORD_BIG_ENDIAN"},
    {REG_LINK, "REG_LINK"},
    {REG_MULTI_SZ, "REG_MULTI_SZ"},
    {REG_RESOURCE_LIST, "REG_RESOURCE_LIST"},
    {REG_FULL_RESOURCE_DESCRIPTOR, "REG_FULL_RESOURCE_DESCRIPTOR"},
    {REG_RESOURCE_REQUIREMENTS_LIST, "REG_RESOURCE_REQUIREMENTS_LIST"},
    {REG_QWORD, "REG_QWORD"},
    {0, NULL},
};

static const flag_repr_t _NtSetValueKey_Type_bitmask[] = {
    {0, NULL},
};

static const flag_repr_t _REGISTRY_VALUE_TYPE_value[] = {
    {REG_NONE, "REG_NONE"},
    {REG_SZ, "REG_SZ"},
    {REG_EXPAND_SZ, "REG_EXPAND_SZ"},
    {REG_BINARY, "REG_BINARY"},
    {REG_DWORD, "REG_DWORD"},
    {REG_DWORD_BIG_ENDIAN, "REG_DWORD_BIG_ENDIAN"},
    {REG_LINK, "REG_LINK"},
    {REG_MULTI_SZ, "REG_MULTI_SZ"},
    {REG_RESOURCE_LIST, "REG_RESOURCE_LIST"},
    {REG_FULL_RESOURCE_DESCRIPTOR, "REG_FULL_RESOURCE_DESCRIPTOR"},
    {REG_RESOURCE_REQUIREMENTS_LIST, "REG_RESOURCE_REQUIREMENTS_LIST"},
    {REG_QWORD, "REG_QWORD"},
    {0, NULL},
};

static const flag_repr_t _REGISTRY_VALUE_TYPE_bitmask[] = {
    {0, NULL},
};

static const flag_repr_t _CreateWindowExA_dwStyle_value[] = {
    {WS_OVERLAPPEDWINDOW, "WS_OVERLAPPEDWINDOW"},
    {WS_POPUPWINDOW, "WS_POPUPWINDOW"},
    {0, NULL},
};

static const flag_repr_t _CreateWindowExA_dwStyle_bitmask[] = {
    {WS_OVERLAPPED, "WS_OVERLAPPED"},
    {WS_POPUP, "WS_POPUP"},
    {WS_CHILD, "WS_CHILD"},
    {WS_MINIMIZE, "WS_MINIMIZE"},
    {WS_VISIBLE, "WS_VISIBLE"},
    {WS_DISABLED, "WS_DISABLED"},
    {WS_CLIPSIBLINGS, "WS_CLIPSIBLINGS"},
    {WS_CLIPCHILDREN, "WS_CLIPCHILDREN"},
    {WS_MAXIMIZE, "WS_MAXIMIZE"},
    {WS_CAPTION, "WS_CAPTION"},
    {WS_BORDER, "WS_BORDER"},
    {WS_DLGFRAME, "WS_DLGFRAME"},
    {WS_VSCROLL, "WS_VSCROLL"},
    {WS_HSCROLL, "WS_HSCROLL"},
    {WS_SYSMENU, "WS_SYSMENU"},
    {WS_THICKFRAME, "WS_THICKFRAME"},
    {WS_GROUP, "WS_GROUP"},
    {WS_TABSTOP, "WS_TABSTOP"},
    {WS_MINIMIZEBOX, "WS_MINIMIZEBOX"},
    {WS_MAXIMIZEBOX, "WS_MAXIMIZEBOX"},
    {0, NULL},
};

static const flag_repr_t _ALG_ID_value[] = {
    {CALG_MD2, "CALG_MD2"},
    {CALG_MD5, "CALG_MD5"},
    {CALG_SHA1, "CALG_SHA1"},
    {CALG_MAC, "CALG_MAC"},
    {CALG_HMAC, "CALG_HMAC"},
    {CALG_SSL3_SHAMD5, "CALG_SSL3_SHAMD5"},
    {CALG_RSA_SIGN, "CALG_RSA_SIGN"},
    {CALG_RSA_KEYX, "CALG_RSA_KEYX"},
    {CALG_RC2, "CALG_RC2"},
    {CALG_RC4, "CALG_RC4"},
    {CALG_DES, "CALG_DES"},
    {CALG_3DES, "CALG_3DES"},
    {CALG_3DES_112, "CALG_3DES_112"},
    {0, NULL},
};

static const flag_repr_t _ALG_ID_bitmask[] = {
    {0, NULL},
};

static const flag_repr_t _KEY_VALUE_INFORMATION_CLASS_value[] = {
    {KeyValueBasicInformation, "KeyValueBasicInformation"},
    {KeyValueFullInformation, "KeyValueFullInformation"},
    {KeyValuePartialInformation, "KeyValuePartialInformation"},
    {KeyValueFullInformationAlign64, "KeyValueFullInformationAlign64"},
    {KeyValuePartialInformationAlign64, "KeyValuePartialInformationAlign64"},
    {MaxKeyValueInfoClass, "MaxKeyValueInfoClass"},
    {0, NULL},
};

static const flag_repr_t _KEY_VALUE_INFORMATION_CLASS_bitmask[] = {
    {0, NULL},
};

static const flag_repr_t _IOCTL_CODES_value[] = {
    {IOCTL_STORAGE_CHECK_VERIFY, "IOCTL_STORAGE_CHECK_VERIFY"},
    {IOCTL_STORAGE_CHECK_VERIFY2, "IOCTL_STORAGE_CHECK_VERIFY2"},
    {IOCTL_STORAGE_MEDIA_REMOVAL, "IOCTL_STORAGE_MEDIA_REMOVAL"},
    {IOCTL_STORAGE_EJECT_MEDIA, "IOCTL_STORAGE_EJECT_MEDIA"},
    {IOCTL_STORAGE_LOAD_MEDIA, "IOCTL_STORAGE_LOAD_MEDIA"},
    {IOCTL_STORAGE_LOAD_MEDIA2, "IOCTL_STORAGE_LOAD_MEDIA2"},
    {IOCTL_STORAGE_RESERVE, "IOCTL_STORAGE_RESERVE"},
    {IOCTL_STORAGE_RELEASE, "IOCTL_STORAGE_RELEASE"},
    {IOCTL_STORAGE_FIND_NEW_DEVICES, "IOCTL_STORAGE_FIND_NEW_DEVICES"},
    {IOCTL_STORAGE_EJECTION_CONTROL, "IOCTL_STORAGE_EJECTION_CONTROL"},
    {IOCTL_STORAGE_MCN_CONTROL, "IOCTL_STORAGE_MCN_CONTROL"},
    {IOCTL_STORAGE_GET_MEDIA_TYPES, "IOCTL_STORAGE_GET_MEDIA_TYPES"},
    {IOCTL_STORAGE_GET_MEDIA_TYPES_EX, "IOCTL_STORAGE_GET_MEDIA_TYPES_EX"},
    {IOCTL_STORAGE_GET_MEDIA_SERIAL_NUMBER, "IOCTL_STORAGE_GET_MEDIA_SERIAL_NUMBER"},
    {IOCTL_STORAGE_GET_HOTPLUG_INFO, "IOCTL_STORAGE_GET_HOTPLUG_INFO"},
    {IOCTL_STORAGE_SET_HOTPLUG_INFO, "IOCTL_STORAGE_SET_HOTPLUG_INFO"},
    {IOCTL_STORAGE_RESET_BUS, "IOCTL_STORAGE_RESET_BUS"},
    {IOCTL_STORAGE_RESET_DEVICE, "IOCTL_STORAGE_RESET_DEVICE"},
    {IOCTL_STORAGE_BREAK_RESERVATION, "IOCTL_STORAGE_BREAK_RESERVATION"},
    {IOCTL_STORAGE_GET_DEVICE_NUMBER, "IOCTL_STORAGE_GET_DEVICE_NUMBER"},
    {IOCTL_STORAGE_PREDICT_FAILURE, "IOCTL_STORAGE_PREDICT_FAILURE"},
    {IOCTL_STORAGE_READ_CAPACITY, "IOCTL_STORAGE_READ_CAPACITY"},
    {IOCTL_DISK_GET_DRIVE_GEOMETRY, "IOCTL_DISK_GET_DRIVE_GEOMETRY"},
    {IOCTL_DISK_GET_PARTITION_INFO, "IOCTL_DISK_GET_PARTITION_INFO"},
    {IOCTL_DISK_SET_PARTITION_INFO, "IOCTL_DISK_SET_PARTITION_INFO"},
    {IOCTL_DISK_GET_DRIVE_LAYOUT, "IOCTL_DISK_GET_DRIVE_LAYOUT"},
    {IOCTL_DISK_SET_DRIVE_LAYOUT, "IOCTL_DISK_SET_DRIVE_LAYOUT"},
    {IOCTL_DISK_VERIFY, "IOCTL_DISK_VERIFY"},
    {IOCTL_DISK_FORMAT_TRACKS, "IOCTL_DISK_FORMAT_TRACKS"},
    {IOCTL_DISK_REASSIGN_BLOCKS, "IOCTL_DISK_REASSIGN_BLOCKS"},
    {IOCTL_DISK_PERFORMANCE, "IOCTL_DISK_PERFORMANCE"},
    {IOCTL_DISK_IS_WRITABLE, "IOCTL_DISK_IS_WRITABLE"},
    {IOCTL_DISK_LOGGING, "IOCTL_DISK_LOGGING"},
    {IOCTL_DISK_FORMAT_TRACKS_EX, "IOCTL_DISK_FORMAT_TRACKS_EX"},
    {IOCTL_DISK_HISTOGRAM_STRUCTURE, "IOCTL_DISK_HISTOGRAM_STRUCTURE"},
    {IOCTL_DISK_HISTOGRAM_DATA, "IOCTL_DISK_HISTOGRAM_DATA"},
    {IOCTL_DISK_HISTOGRAM_RESET, "IOCTL_DISK_HISTOGRAM_RESET"},
    {IOCTL_DISK_REQUEST_STRUCTURE, "IOCTL_DISK_REQUEST_STRUCTURE"},
    {IOCTL_DISK_REQUEST_DATA, "IOCTL_DISK_REQUEST_DATA"},
    {IOCTL_DISK_PERFORMANCE_OFF, "IOCTL_DISK_PERFORMANCE_OFF"},
    {IOCTL_DISK_CONTROLLER_NUMBER, "IOCTL_DISK_CONTROLLER_NUMBER"},
    {IOCTL_DISK_GET_PARTITION_INFO_EX, "IOCTL_DISK_GET_PARTITION_INFO_EX"},
    {IOCTL_DISK_SET_PARTITION_INFO_EX, "IOCTL_DISK_SET_PARTITION_INFO_EX"},
    {IOCTL_DISK_GET_DRIVE_LAYOUT_EX, "IOCTL_DISK_GET_DRIVE_LAYOUT_EX"},
    {IOCTL_DISK_SET_DRIVE_LAYOUT_EX, "IOCTL_DISK_SET_DRIVE_LAYOUT_EX"},
    {IOCTL_DISK_CREATE_DISK, "IOCTL_DISK_CREATE_DISK"},
    {IOCTL_DISK_GET_LENGTH_INFO, "IOCTL_DISK_GET_LENGTH_INFO"},
    {IOCTL_DISK_GET_DRIVE_GEOMETRY_EX, "IOCTL_DISK_GET_DRIVE_GEOMETRY_EX"},
    {IOCTL_DISK_REASSIGN_BLOCKS_EX, "IOCTL_DISK_REASSIGN_BLOCKS_EX"},
    {IOCTL_DISK_UPDATE_DRIVE_SIZE, "IOCTL_DISK_UPDATE_DRIVE_SIZE"},
    {IOCTL_DISK_GROW_PARTITION, "IOCTL_DISK_GROW_PARTITION"},
    {IOCTL_DISK_GET_CACHE_INFORMATION, "IOCTL_DISK_GET_CACHE_INFORMATION"},
    {IOCTL_DISK_SET_CACHE_INFORMATION, "IOCTL_DISK_SET_CACHE_INFORMATION"},
    {IOCTL_DISK_DELETE_DRIVE_LAYOUT, "IOCTL_DISK_DELETE_DRIVE_LAYOUT"},
    {IOCTL_DISK_UPDATE_PROPERTIES, "IOCTL_DISK_UPDATE_PROPERTIES"},
    {IOCTL_DISK_RESET_SNAPSHOT_INFO, "IOCTL_DISK_RESET_SNAPSHOT_INFO"},
    {IOCTL_DISK_FORMAT_DRIVE, "IOCTL_DISK_FORMAT_DRIVE"},
    {IOCTL_DISK_SENSE_DEVICE, "IOCTL_DISK_SENSE_DEVICE"},
    {IOCTL_DISK_CHECK_VERIFY, "IOCTL_DISK_CHECK_VERIFY"},
    {IOCTL_DISK_MEDIA_REMOVAL, "IOCTL_DISK_MEDIA_REMOVAL"},
    {IOCTL_DISK_EJECT_MEDIA, "IOCTL_DISK_EJECT_MEDIA"},
    {IOCTL_DISK_LOAD_MEDIA, "IOCTL_DISK_LOAD_MEDIA"},
    {IOCTL_DISK_RESERVE, "IOCTL_DISK_RESERVE"},
    {IOCTL_DISK_RELEASE, "IOCTL_DISK_RELEASE"},
    {IOCTL_DISK_FIND_NEW_DEVICES, "IOCTL_DISK_FIND_NEW_DEVICES"},
    {IOCTL_DISK_GET_MEDIA_TYPES, "IOCTL_DISK_GET_MEDIA_TYPES"},
    {0, NULL},
};

static const flag_repr_t _IOCTL_CODES_bitmask[] = {
    {0, NULL},
};

static const flag_repr_t _VirtualProtectEx_flNewProtect_value[] = {
    {0, NULL},
};

static const flag_repr_t _VirtualProtectEx_flNewProtect_bitmask[] = {
    {PAGE_EXECUTE, "PAGE_EXECUTE"},
    {PAGE_EXECUTE_READ, "PAGE_EXECUTE_READ"},
    {PAGE_EXECUTE_READWRITE, "PAGE_EXECUTE_READWRITE"},
    {PAGE_EXECUTE_WRITECOPY, "PAGE_EXECUTE_WRITECOPY"},
    {PAGE_NOACCESS, "PAGE_NOACCESS"},
    {PAGE_READONLY, "PAGE_READONLY"},
    {PAGE_READWRITE, "PAGE_READWRITE"},
    {PAGE_WRITECOPY, "PAGE_WRITECOPY"},
    {PAGE_GUARD, "PAGE_GUARD"},
    {PAGE_NOCACHE, "PAGE_NOCACHE"},
    {PAGE_WRITECOMBINE, "PAGE_WRITECOMBINE"},
    {0, NULL},
};

static const flag_repr_t _CreateProcessInternalW_creation_flags_value[] = {
    {0, NULL},
};

static const flag_repr_t _CreateProcessInternalW_creation_flags_bitmask[] = {
    {CREATE_BREAKAWAY_FROM_JOB, "CREATE_BREAKAWAY_FROM_JOB"},
    {CREATE_DEFAULT_ERROR_MODE, "CREATE_DEFAULT_ERROR_MODE"},
    {CREATE_NEW_CONSOLE, "CREATE_NEW_CONSOLE"},
    {CREATE_NEW_PROCESS_GROUP, "CREATE_NEW_PROCESS_GROUP"},
    {CREATE_NO_WINDOW, "CREATE_NO_WINDOW"},
    {CREATE_PROTECTED_PROCESS, "CREATE_PROTECTED_PROCESS"},
    {CREATE_PRESERVE_CODE_AUTHZ_LEVEL, "CREATE_PRESERVE_CODE_AUTHZ_LEVEL"},
    {CREATE_SEPARATE_WOW_VDM, "CREATE_SEPARATE_WOW_VDM"},
    {CREATE_SHARED_WOW_VDM, "CREATE_SHARED_WOW_VDM"},
    {CREATE_SUSPENDED, "CREATE_SUSPENDED"},
    {CREATE_UNICODE_ENVIRONMENT, "CREATE_UNICODE_ENVIRONMENT"},
    {DEBUG_ONLY_THIS_PROCESS, "DEBUG_ONLY_THIS_PROCESS"},
    {DEBUG_PROCESS, "DEBUG_PROCESS"},
    {DETACHED_PROCESS, "DETACHED_PROCESS"},
    {EXTENDED_STARTUPINFO_PRESENT, "EXTENDED_STARTUPINFO_PRESENT"},
    {INHERIT_PARENT_AFFINITY, "INHERIT_PARENT_AFFINITY"},
    {ABOVE_NORMAL_PRIORITY_CLASS, "ABOVE_NORMAL_PRIORITY_CLASS"},
    {BELOW_NORMAL_PRIORITY_CLASS, "BELOW_NORMAL_PRIORITY_CLASS"},
    {HIGH_PRIORITY_CLASS, "HIGH_PRIORITY_CLASS"},
    {IDLE_PRIORITY_CLASS, "IDLE_PRIORITY_CLASS"},
    {NORMAL_PRIORITY_CLASS, "NORMAL_PRIORITY_CLASS"},
    {REALTIME_PRIORITY_CLASS, "REALTIME_PRIORITY_CLASS"},
    {0, NULL},
};

static const flag_repr_t _KEY_INFORMATION_CLASS_value[] = {
    {KeyBasicInformation, "KeyBasicInformation"},
    {KeyNodeInformation, "KeyNodeInformation"},
    {KeyFullInformation, "KeyFullInformation"},
    {KeyNameInformation, "KeyNameInformation"},
    {KeyCachedInformation, "KeyCachedInformation"},
    {KeyFlagsInformation, "KeyFlagsInformation"},
    {KeyVirtualizationInformation, "KeyVirtualizationInformation"},
    {KeyHandleTagsInformation, "KeyHandleTagsInformation"},
    {0, NULL},
};

static const flag_repr_t _KEY_INFORMATION_CLASS_bitmask[] = {
    {0, NULL},
};

static const flag_repr_t _FileOptions_value[] = {
    {0, NULL},
};

static const flag_repr_t _FileOptions_bitmask[] = {
    {FILE_DIRECTORY_FILE, "FILE_DIRECTORY_FILE"},
    {FILE_NON_DIRECTORY_FILE, "FILE_NON_DIRECTORY_FILE"},
    {FILE_WRITE_THROUGH, "FILE_WRITE_THROUGH"},
    {FILE_SEQUENTIAL_ONLY, "FILE_SEQUENTIAL_ONLY"},
    {FILE_RANDOM_ACCESS, "FILE_RANDOM_ACCESS"},
    {FILE_NO_INTERMEDIATE_BUFFERING, "FILE_NO_INTERMEDIATE_BUFFERING"},
    {FILE_SYNCHRONOUS_IO_ALERT, "FILE_SYNCHRONOUS_IO_ALERT"},
    {FILE_SYNCHRONOUS_IO_NONALERT, "FILE_SYNCHRONOUS_IO_NONALERT"},
    {FILE_CREATE_TREE_CONNECTION, "FILE_CREATE_TREE_CONNECTION"},
    {FILE_COMPLETE_IF_OPLOCKED, "FILE_COMPLETE_IF_OPLOCKED"},
    {FILE_NO_EA_KNOWLEDGE, "FILE_NO_EA_KNOWLEDGE"},
    {FILE_OPEN_REPARSE_POINT, "FILE_OPEN_REPARSE_POINT"},
    {FILE_DELETE_ON_CLOSE, "FILE_DELETE_ON_CLOSE"},
    {FILE_OPEN_BY_FILE_ID, "FILE_OPEN_BY_FILE_ID"},
    {FILE_OPEN_FOR_BACKUP_INTENT, "FILE_OPEN_FOR_BACKUP_INTENT"},
    {FILE_RESERVE_OPFILTER, "FILE_RESERVE_OPFILTER"},
    {0, NULL},
};

static const flag_repr_t _FILE_INFO_BY_HANDLE_CLASS_value[] = {
    {FileBasicInfo, "FileBasicInfo"},
    {FileStandardInfo, "FileStandardInfo"},
    {FileNameInfo, "FileNameInfo"},
    {FileRenameInfo, "FileRenameInfo"},
    {FileDispositionInfo, "FileDispositionInfo"},
    {FileAllocationInfo, "FileAllocationInfo"},
    {FileEndOfFileInfo, "FileEndOfFileInfo"},
    {FileStreamInfo, "FileStreamInfo"},
    {FileCompressionInfo, "FileCompressionInfo"},
    {FileAttributeTagInfo, "FileAttributeTagInfo"},
    {FileIdBothDirectoryInfo, "FileIdBothDirectoryInfo"},
    {FileIdBothDirectoryRestartInfo, "FileIdBothDirectoryRestartInfo"},
    {FileIoPriorityHintInfo, "FileIoPriorityHintInfo"},
    {FileRemoteProtocolInfo, "FileRemoteProtocolInfo"},
    {FileFullDirectoryInfo, "FileFullDirectoryInfo"},
    {FileFullDirectoryRestartInfo, "FileFullDirectoryRestartInfo"},
    {FileStorageInfo, "FileStorageInfo"},
    {FileAlignmentInfo, "FileAlignmentInfo"},
    {FileIdInfo, "FileIdInfo"},
    {FileIdExtdDirectoryInfo, "FileIdExtdDirectoryInfo"},
    {FileIdExtdDirectoryRestartInfo, "FileIdExtdDirectoryRestartInfo"},
    {0, NULL},
};

static const flag_repr_t _FILE_INFO_BY_HANDLE_CLASS_bitmask[] = {
    {0, NULL},
};

static const flag_repr_t _CreateWindowExW_dwStyle_value[] = {
    {WS_OVERLAPPEDWINDOW, "WS_OVERLAPPEDWINDOW"},
    {WS_POPUPWINDOW, "WS_POPUPWINDOW"},
    {0, NULL},
};

static const flag_repr_t _CreateWindowExW_dwStyle_bitmask[] = {
    {WS_OVERLAPPED, "WS_OVERLAPPED"},
    {WS_POPUP, "WS_POPUP"},
    {WS_CHILD, "WS_CHILD"},
    {WS_MINIMIZE, "WS_MINIMIZE"},
    {WS_VISIBLE, "WS_VISIBLE"},
    {WS_DISABLED, "WS_DISABLED"},
    {WS_CLIPSIBLINGS, "WS_CLIPSIBLINGS"},
    {WS_CLIPCHILDREN, "WS_CLIPCHILDREN"},
    {WS_MAXIMIZE, "WS_MAXIMIZE"},
    {WS_CAPTION, "WS_CAPTION"},
    {WS_BORDER, "WS_BORDER"},
    {WS_DLGFRAME, "WS_DLGFRAME"},
    {WS_VSCROLL, "WS_VSCROLL"},
    {WS_HSCROLL, "WS_HSCROLL"},
    {WS_SYSMENU, "WS_SYSMENU"},
    {WS_THICKFRAME, "WS_THICKFRAME"},
    {WS_GROUP, "WS_GROUP"},
    {WS_TABSTOP, "WS_TABSTOP"},
    {WS_MINIMIZEBOX, "WS_MINIMIZEBOX"},
    {WS_MAXIMIZEBOX, "WS_MAXIMIZEBOX"},
    {0, NULL},
};

static const flag_repr_t _SetWindowsHookExA_idHook_value[] = {
    {WH_JOURNALRECORD, "WH_JOURNALRECORD"},
    {WH_JOURNALPLAYBACK, "WH_JOURNALPLAYBACK"},
    {WH_KEYBOARD, "WH_KEYBOARD"},
    {WH_GETMESSAGE, "WH_GETMESSAGE"},
    {WH_CALLWNDPROC, "WH_CALLWNDPROC"},
    {WH_CBT, "WH_CBT"},
    {WH_SYSMSGFILTER, "WH_SYSMSGFILTER"},
    {WH_MOUSE, "WH_MOUSE"},
    {WH_HARDWARE, "WH_HARDWARE"},
    {WH_DEBUG, "WH_DEBUG"},
    {WH_SHELL, "WH_SHELL"},
    {WH_FOREGROUNDIDLE, "WH_FOREGROUNDIDLE"},
    {WH_CALLWNDPROCRET, "WH_CALLWNDPROCRET"},
    {WH_KEYBOARD_LL, "WH_KEYBOARD_LL"},
    {WH_MOUSE_LL, "WH_MOUSE_LL"},
    {0, NULL},
};

static const flag_repr_t _SetWindowsHookExA_idHook_bitmask[] = {
    {0, NULL},
};


const flag_repr_t *g_flags[FLAGCNT][2] = {
    {NULL, NULL},
    {_NtQueryValueKey_reg_type_value, _NtQueryValueKey_reg_type_bitmask},
    {_RegQueryValueExW_lpType_value, _RegQueryValueExW_lpType_bitmask},
    {_RegQueryValueExA_lpType_value, _RegQueryValueExA_lpType_bitmask},
    {_NtAllocateVirtualMemory_Protect_value, _NtAllocateVirtualMemory_Protect_bitmask},
    {_InternetQueryOptions_value, _InternetQueryOptions_bitmask},
    {_RegSetValueExA_dwType_value, _RegSetValueExA_dwType_bitmask},
    {_FILE_INFORMATION_CLASS_value, _FILE_INFORMATION_CLASS_bitmask},
    {_NtCreateFile_FileAttributes_value, _NtCreateFile_FileAttributes_bitmask},
    {_SetFileAttributesW_dwFileAttributes_value, _SetFileAttributesW_dwFileAttributes_bitmask},
    {_NtCreateFile_DesiredAccess_value, _NtCreateFile_DesiredAccess_bitmask},
    {_NtOpenFile_OpenOptions_value, _NtOpenFile_OpenOptions_bitmask},
    {_NtCreateFile_CreateOptions_value, _NtCreateFile_CreateOptions_bitmask},
    {_NtOpenFile_DesiredAccess_value, _NtOpenFile_DesiredAccess_bitmask},
    {_NtEnumerateValueKey_reg_type_value, _NtEnumerateValueKey_reg_type_bitmask},
    {_CreateWindowExW_dwExStyle_value, _CreateWindowExW_dwExStyle_bitmask},
    {_GetSystemMetrics_nIndex_value, _GetSystemMetrics_nIndex_bitmask},
    {_NtMapViewOfSection_AllocationType_value, _NtMapViewOfSection_AllocationType_bitmask},
    {_NtDeviceIoControlFile_IoControlCode_value, _NtDeviceIoControlFile_IoControlCode_bitmask},
    {_MemoryProtectionFlags_value, _MemoryProtectionFlags_bitmask},
    {_RegEnumValueA_lpType_value, _RegEnumValueA_lpType_bitmask},
    {_InternetQueryOptionA_dwOption_value, _InternetQueryOptionA_dwOption_bitmask},
    {_NtAllocateVirtualMemory_AllocationType_value, _NtAllocateVirtualMemory_AllocationType_bitmask},
    {_NtProtectVirtualMemory_NewAccessProtection_value, _NtProtectVirtualMemory_NewAccessProtection_bitmask},
    {_InternetSetOptionA_dwOption_value, _InternetSetOptionA_dwOption_bitmask},
    {_NtCreateFile_CreateDisposition_value, _NtCreateFile_CreateDisposition_bitmask},
    {_PRIORITY_CLASS_value, _PRIORITY_CLASS_bitmask},
    {_NtOpenFile_ShareAccess_value, _NtOpenFile_ShareAccess_bitmask},
    {_AllocationType_value, _AllocationType_bitmask},
    {_WindowStyles_value, _WindowStyles_bitmask},
    {_SetErrorMode_uMode_value, _SetErrorMode_uMode_bitmask},
    {_RegSetValueExW_dwType_value, _RegSetValueExW_dwType_bitmask},
    {_CreateWindowExA_dwExStyle_value, _CreateWindowExA_dwExStyle_bitmask},
    {_ExtendedWindowStyles_value, _ExtendedWindowStyles_bitmask},
    {_NtCreateFile_ShareAccess_value, _NtCreateFile_ShareAccess_bitmask},
    {_ShareAccessFlags_value, _ShareAccessFlags_bitmask},
    {_RegEnumValueW_lpType_value, _RegEnumValueW_lpType_bitmask},
    {_WINDOWS_HOOKS_value, _WINDOWS_HOOKS_bitmask},
    {_SHGetFolderPathW_nFolder_value, _SHGetFolderPathW_nFolder_bitmask},
    {_SetWindowsHookExW_idHook_value, _SetWindowsHookExW_idHook_bitmask},
    {_DeviceIoControl_dwIoControlCode_value, _DeviceIoControl_dwIoControlCode_bitmask},
    {_ACCESS_MASK_value, _ACCESS_MASK_bitmask},
    {_NtSetValueKey_Type_value, _NtSetValueKey_Type_bitmask},
    {_REGISTRY_VALUE_TYPE_value, _REGISTRY_VALUE_TYPE_bitmask},
    {_CreateWindowExA_dwStyle_value, _CreateWindowExA_dwStyle_bitmask},
    {_ALG_ID_value, _ALG_ID_bitmask},
    {_KEY_VALUE_INFORMATION_CLASS_value, _KEY_VALUE_INFORMATION_CLASS_bitmask},
    {_IOCTL_CODES_value, _IOCTL_CODES_bitmask},
    {_VirtualProtectEx_flNewProtect_value, _VirtualProtectEx_flNewProtect_bitmask},
    {_CreateProcessInternalW_creation_flags_value, _CreateProcessInternalW_creation_flags_bitmask},
    {_KEY_INFORMATION_CLASS_value, _KEY_INFORMATION_CLASS_bitmask},
    {_FileOptions_value, _FileOptions_bitmask},
    {_FILE_INFO_BY_HANDLE_CLASS_value, _FILE_INFO_BY_HANDLE_CLASS_bitmask},
    {_CreateWindowExW_dwStyle_value, _CreateWindowExW_dwStyle_bitmask},
    {_SetWindowsHookExA_idHook_value, _SetWindowsHookExA_idHook_bitmask},
};

const flag_repr_t *flag_value(uint32_t flagidx)
{
    return g_flags[flagidx][0];
}

const flag_repr_t *flag_bitmask(uint32_t flagidx)
{
    return g_flags[flagidx][1];
}
